module.exports = [
	{
		"": "",
		companyCode: "VIC",
		companyName: "Công ty Cổ phần Vingroup",
		industryId: "1907",
		industryCodeLevel3: "701",
		industryCodeLevel2: "70",
		companyId: "1",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "NVL",
		companyName: "Công ty Cổ phần Địa ốc No Va",
		industryId: "1890",
		industryCodeLevel3: "681",
		industryCodeLevel2: "68",
		companyId: "2",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "DXG",
		companyName: "Công ty Cổ phần Tập đoàn Đất Xanh",
		industryId: "1890",
		industryCodeLevel3: "681",
		industryCodeLevel2: "68",
		companyId: "3",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "FLC",
		companyName: "Công ty Cổ phần Tập đoàn FLC",
		industryId: "1890",
		industryCodeLevel3: "681",
		industryCodeLevel2: "68",
		companyId: "4",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "VCI",
		companyName: "Công ty Cổ phần Chứng khoán Bản Việt",
		industryId: "1879",
		industryCodeLevel3: "661",
		industryCodeLevel2: "66",
		companyId: "6",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "SSI",
		companyName: "Công ty Cổ phần Chứng khoán Sài Gòn",
		industryId: "1879",
		industryCodeLevel3: "661",
		industryCodeLevel2: "66",
		companyId: "7",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "VDS",
		companyName: "Công ty Cổ phần Chứng khoán Rồng Việt",
		industryId: "1879",
		industryCodeLevel3: "661",
		industryCodeLevel2: "66",
		companyId: "8",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "VND",
		companyName: "Công ty Cổ phần Chứng khoán VNDirect",
		industryId: "1879",
		industryCodeLevel3: "661",
		industryCodeLevel2: "66",
		companyId: "9",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HCM",
		companyName: "Công ty Cổ phần Chứng khoán TP.HCM",
		industryId: "1879",
		industryCodeLevel3: "661",
		industryCodeLevel2: "66",
		companyId: "10",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "VIX",
		companyName: "Công ty Cổ phần Chứng khoán VIX",
		industryId: "1879",
		industryCodeLevel3: "661",
		industryCodeLevel2: "66",
		companyId: "11",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "ORS",
		companyName: "Công ty Cổ phần Chứng khoán Phương Đông",
		industryId: "1879",
		industryCodeLevel3: "661",
		industryCodeLevel2: "66",
		companyId: "12",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "TVB",
		companyName: "Công ty Cổ phần Chứng khoán Trí Việt",
		industryId: "1879",
		industryCodeLevel3: "661",
		industryCodeLevel2: "66",
		companyId: "13",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "MBS",
		companyName: "Công ty Cổ phần Chứng khoán MB",
		industryId: "1879",
		industryCodeLevel3: "661",
		industryCodeLevel2: "66",
		companyId: "14",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "KIS",
		companyName: "Công ty Cổ phần Chứng khoán KIS Việt Nam",
		industryId: "1879",
		industryCodeLevel3: "661",
		industryCodeLevel2: "66",
		companyId: "15",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "VNZ",
		companyName: "Công ty Cổ phần VNG",
		industryId: "1852",
		industryCodeLevel3: "631",
		industryCodeLevel2: "63",
		companyId: "16",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "FPT",
		companyName: "Công ty Cổ phần FPT",
		industryId: "1847",
		industryCodeLevel3: "620",
		industryCodeLevel2: "62",
		companyId: "17",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "PNJ",
		companyName: "Công ty Cổ phần Vàng bạc Đá quý Phú Nhuận (PNJ)",
		industryId: "1642",
		industryCodeLevel3: "477",
		industryCodeLevel2: "47",
		companyId: "18",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "DOJ",
		companyName: "Công ty Cổ phần Tập đoàn Vàng bạc Đá quý DOJI",
		industryId: "1642",
		industryCodeLevel3: "477",
		industryCodeLevel2: "47",
		companyId: "19",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "SJC",
		companyName: "Công ty Cổ phần Vàng bạc Đá quý SJC",
		industryId: "1642",
		industryCodeLevel3: "477",
		industryCodeLevel2: "47",
		companyId: "20",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "STC",
		companyName: "Công ty Cổ phần Sách và Thiết bị Trường học Hà Nội",
		industryId: "1637",
		industryCodeLevel3: "476",
		industryCodeLevel2: "47",
		companyId: "21",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "AFA",
		companyName: "Công ty Cổ phần Sách Alpha",
		industryId: "1637",
		industryCodeLevel3: "476",
		industryCodeLevel2: "47",
		companyId: "22",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "DUC",
		companyName: "Công ty Cổ phần Sách Đại học",
		industryId: "1637",
		industryCodeLevel3: "476",
		industryCodeLevel2: "47",
		companyId: "23",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "STP",
		companyName: "Công ty Cổ phần Sách và Thiết bị Trường học TP.HCM",
		industryId: "1637",
		industryCodeLevel3: "476",
		industryCodeLevel2: "47",
		companyId: "24",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "AEON",
		companyName: "Aeon Mall",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "25",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "B4B",
		companyName: "Metro AG",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "26",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "KRX004990",
		companyName: "Lotte",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "27",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "CRC",
		companyName: "Central Retail",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "28",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "WMT",
		companyName: "Walmart",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "29",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "BJC",
		companyName: "BJC Group",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "30",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "FRT",
		companyName: "Công ty Cổ phần Bán lẻ Kỹ thuật số FPT",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "31",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "MWG",
		companyName: "Công ty Cổ phần Thế Giới Di Động",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "32",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "VRE",
		companyName: "Công ty Cổ phần Thương mại Điện tử Bán lẻ Việt Nam",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "33",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "CGG",
		companyName: "Công ty Cổ phần Thương mại Dịch vụ Cổng Vàng",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "34",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "SAS",
		companyName: "Công ty Cổ phần Dịch vụ Tổng hợp Sài Gòn",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "35",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "VEC",
		companyName: "Công ty Cổ phần Thương mại Điện tử VinGroup",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "36",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "NBS",
		companyName: "Công ty Cổ phần Dịch vụ Tổng hợp Miền Bắc",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "37",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "VMG",
		companyName: "Công ty Cổ phần Thương mại Điện tử VinMart",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "38",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "VMS",
		companyName: "Công ty Cổ phần Thương mại Điện tử VinSmart",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "39",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "PYS",
		companyName: "Công ty Cổ phần Dịch vụ Tổng hợp Phú Yên",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "40",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "BNE",
		companyName: "Công ty Cổ phần Thương mại Điện tử Bắc Ninh",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "41",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "KHS",
		companyName: "Công ty Cổ phần Dịch vụ Tổng hợp Khánh Hòa",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "42",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HTS",
		companyName: "Công ty Cổ phần Dịch vụ Tổng hợp Hà Tĩnh",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "43",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "BTS",
		companyName: "Công ty Cổ phần Dịch vụ Tổng hợp Bình Thuận",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "44",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "QBS",
		companyName: "Công ty Cổ phần Thương mại Điện tử Quảng Bình",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "45",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "DNS",
		companyName: "Công ty Cổ phần Thương mại Điện tử Đồng Nai",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "46",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "VCM",
		companyName: "Công ty Cổ phần Dịch vụ Bán lẻ Tổng hợp VinCommerce",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "48",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "PTC",
		companyName: "Công ty Cổ phần Tập đoàn Phú Thái",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "49",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "NKC",
		companyName: "Công ty Cổ phần Tập đoàn Nguyễn Kim",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "51",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "SAT",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Sài Gòn",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "52",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HSM",
		companyName: "Công ty Cổ phần Siêu thị Hà Nội",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "53",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HAT",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Hà Nội",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "54",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "QNS",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Quảng Ninh",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "55",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "MBM",
		companyName: "Công ty Cổ phần Siêu thị Miền Bắc",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "56",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "DNG",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Đà Nẵng",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "57",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "MTC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Miền Trung",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "58",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "BDC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Bình Dương",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "59",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "BET",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Bến Tre",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "60",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "NDC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Nam Định",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "61",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HUE",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Huế",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "62",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HPC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Hải Phòng",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "63",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "TBC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Thái Bình",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "64",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "VPC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Vĩnh Phúc",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "65",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "LDC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Lâm Đồng",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "66",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HGC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Hậu Giang",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "67",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "LAC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Long An",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "69",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "TGC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Tiền Giang",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "70",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "CTC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Cần Thơ",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "71",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "AGC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp An Giang",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "72",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "TVC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Trà Vinh",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "74",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "BLC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Bạc Liêu",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "75",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "CMC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Cà Mau",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "76",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "KGC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Kiên Giang",
		industryId: "1594",
		industryCodeLevel3: "471",
		industryCodeLevel2: "47",
		companyId: "77",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "DP3",
		companyName: "Công ty Cổ phần Dược phẩm Trung ương 3",
		industryId: "1536",
		industryCodeLevel3: "464",
		industryCodeLevel2: "46",
		companyId: "79",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "CTD",
		companyName: "Công ty Cổ phần Xây dựng Coteccons",
		industryId: "1457",
		industryCodeLevel3: "410",
		industryCodeLevel2: "41",
		companyId: "80",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HBC",
		companyName: "Công ty Cổ phần Xây dựng Hòa Bình",
		industryId: "1457",
		industryCodeLevel3: "410",
		industryCodeLevel2: "41",
		companyId: "81",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "BWE",
		companyName: "Công ty Cổ phần Đầu tư và Xây dựng Bình Dương",
		industryId: "1457",
		industryCodeLevel3: "410",
		industryCodeLevel2: "41",
		companyId: "83",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "PPC",
		companyName: "Công ty Cổ phần Nhiệt điện Phả Lại",
		industryId: "1418",
		industryCodeLevel3: "351",
		industryCodeLevel2: "35",
		companyId: "84",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "DQC",
		companyName: "Công ty Cổ phần Bóng đèn Điện Quang",
		industryId: "1353",
		industryCodeLevel3: "274",
		industryCodeLevel2: "27",
		companyId: "85",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "RAL",
		companyName: "Công ty Cổ phần Bóng đèn Phích nước Rạng Đông",
		industryId: "1353",
		industryCodeLevel3: "274",
		industryCodeLevel2: "27",
		companyId: "86",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "CEC",
		companyName: "Công ty Cổ phần Cơ điện Trần Phú",
		industryId: "1345",
		industryCodeLevel3: "271",
		industryCodeLevel2: "27",
		companyId: "89",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "BHE",
		companyName: "Công ty Cổ phần Điện tử Bình Hòa",
		industryId: "1345",
		industryCodeLevel3: "271",
		industryCodeLevel2: "27",
		companyId: "90",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HPG",
		companyName: "Công ty Cổ phần Thép Hòa Phát",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "91",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "NKG",
		companyName: "Công ty Cổ phần Thép Nam Kim",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "92",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "TLH",
		companyName: "Công ty Cổ phần Thép Tiến Lên",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "94",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "VIS",
		companyName: "Công ty Cổ phần Thép Việt Ý",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "95",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HSG",
		companyName: "Công ty Cổ phần Tập đoàn Hoa Sen",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "97",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "POM",
		companyName: "Công ty Cổ phần Thép Pomina",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "98",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "TDS",
		companyName: "Công ty Cổ phần Thép Thủ Đức",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "99",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "BVG",
		companyName: "Công ty Cổ phần Thép Bắc Việt",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "100",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "TNB",
		companyName: "Công ty Cổ phần Thép Nhà Bè",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "101",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "TTA",
		companyName: "Công ty Cổ phần Thép Tân Tạo",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "102",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "PMT",
		companyName: "Công ty Cổ phần Thép Phú Mỹ",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "103",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "LBS",
		companyName: "Công ty Cổ phần Thép Long Biên",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "104",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "BHS",
		companyName: "Công ty Cổ phần Thép Biên Hòa",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "105",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HAN",
		companyName: "Công ty Cổ phần Thép Hà Nội",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "106",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "SGN",
		companyName: "Công ty Cổ phần Thép Sài Gòn",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "107",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "DTL",
		companyName: "Công ty Cổ phần Thép Đại Thiên Lộc",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "108",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "TMS",
		companyName: "Công ty Cổ phần Sắt Thép Miền Nam",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "111",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HPS",
		companyName: "Công ty Cổ phần Thép Hải Phòng",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "112",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "PHS",
		companyName: "Công ty Cổ phần Thép Phú Mỹ",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "114",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "NTS",
		companyName: "Công ty Cổ phần Sắt Thép Nha Trang",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "115",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "VTS",
		companyName: "Công ty Cổ phần Thép Vũng Tàu",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "118",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "TNS",
		companyName: "Công ty Cổ phần Thép Thái Nguyên",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "119",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "CPS",
		companyName: "Công ty Cổ phần Thép Cẩm Phả",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "121",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "PTS",
		companyName: "Công ty Cổ phần Thép Phú Thọ",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "122",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "NDS",
		companyName: "Công ty Cổ phần Thép Nam Định",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "123",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "CDS",
		companyName: "Công ty Cổ phần Thép Cầu Diễn",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "124",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HDS",
		companyName: "Công ty Cổ phần Thép Hà Đông",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "125",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HAG",
		companyName: "Công ty Cổ phần Thép Hoàng Anh Gia Lai",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "127",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "GSS",
		companyName: "Công ty Cổ phần Thép Gia Sàng",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "128",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "DAS",
		companyName: "Công ty Cổ phần Thép Đông Anh",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "129",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "MXS",
		companyName: "Công ty Cổ phần Thép Mỹ Xuân",
		industryId: "1313",
		industryCodeLevel3: "241",
		industryCodeLevel2: "24",
		companyId: "131",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HT1",
		companyName: "Công ty Cổ phần Xi măng Hà Tiên 1",
		industryId: "1301",
		industryCodeLevel3: "239",
		industryCodeLevel2: "23",
		companyId: "133",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HTV",
		companyName: "Công ty Cổ phần Xi măng Vicem Hoàng Thạch",
		industryId: "1301",
		industryCodeLevel3: "239",
		industryCodeLevel2: "23",
		companyId: "134",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "BCC",
		companyName: "Công ty Cổ phần Xi măng Bỉm Sơn",
		industryId: "1301",
		industryCodeLevel3: "239",
		industryCodeLevel2: "23",
		companyId: "136",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HOM",
		companyName: "Công ty Cổ phần Xi măng Vicem Hoàng Mai",
		industryId: "1301",
		industryCodeLevel3: "239",
		industryCodeLevel2: "23",
		companyId: "137",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HVX",
		companyName: "Công ty Cổ phần Xi măng Vicem Hải Vân",
		industryId: "1301",
		industryCodeLevel3: "239",
		industryCodeLevel2: "23",
		companyId: "138",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HLC",
		companyName: "Công ty Cổ phần Xi măng Hoàng Long",
		industryId: "1301",
		industryCodeLevel3: "239",
		industryCodeLevel2: "23",
		companyId: "139",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "CLH",
		companyName: "Công ty Cổ phần Xi măng La Hiên",
		industryId: "1301",
		industryCodeLevel3: "239",
		industryCodeLevel2: "23",
		companyId: "141",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HPM",
		companyName: "Công ty Cổ phần Xi măng Hải Phòng",
		industryId: "1301",
		industryCodeLevel3: "239",
		industryCodeLevel2: "23",
		companyId: "143",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "BMP",
		companyName: "Công ty Cổ phần Nhựa Bình Minh",
		industryId: "1292",
		industryCodeLevel3: "222",
		industryCodeLevel2: "22",
		companyId: "144",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "NTP",
		companyName: "Công ty Cổ phần Nhựa Tiền Phong",
		industryId: "1292",
		industryCodeLevel3: "222",
		industryCodeLevel2: "22",
		companyId: "145",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "SRC",
		companyName: "Công ty Cổ phần Cao su Sao Vàng",
		industryId: "1289",
		industryCodeLevel3: "221",
		industryCodeLevel2: "22",
		companyId: "146",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "DRC",
		companyName: "Công ty Cổ phần Cao su Đà Nẵng",
		industryId: "1289",
		industryCodeLevel3: "221",
		industryCodeLevel2: "22",
		companyId: "147",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "DHG",
		companyName: "Công ty Cổ phần Dược Hậu Giang",
		industryId: "1285",
		industryCodeLevel3: "210",
		industryCodeLevel2: "21",
		companyId: "148",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "IMP",
		companyName: "Công ty Cổ phần Dược phẩm Imexpharm",
		industryId: "1285",
		industryCodeLevel3: "210",
		industryCodeLevel2: "21",
		companyId: "149",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "DGC",
		companyName: "Công ty Cổ phần Tập đoàn Hóa chất Đức Giang",
		industryId: "1274",
		industryCodeLevel3: "202",
		industryCodeLevel2: "20",
		companyId: "150",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "TNG",
		companyName: "Công ty Cổ phần Đầu tư và Thương mại TNG",
		industryId: "1229",
		industryCodeLevel3: "141",
		industryCodeLevel2: "14",
		companyId: "151",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "MSH",
		companyName: "Công ty Cổ phần May Sông Hồng",
		industryId: "1229",
		industryCodeLevel3: "141",
		industryCodeLevel2: "14",
		companyId: "152",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "VGG",
		companyName: "Công ty Cổ phần May Việt Tiến",
		industryId: "1229",
		industryCodeLevel3: "141",
		industryCodeLevel2: "14",
		companyId: "153",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "TCM",
		companyName: "Công ty Cổ phần Dệt may Thành Công",
		industryId: "1229",
		industryCodeLevel3: "141",
		industryCodeLevel2: "14",
		companyId: "154",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "M10",
		companyName: "Công ty Cổ phần May 10",
		industryId: "1229",
		industryCodeLevel3: "141",
		industryCodeLevel2: "14",
		companyId: "155",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "MNB",
		companyName: "Công ty Cổ phần May Nhà Bè",
		industryId: "1229",
		industryCodeLevel3: "141",
		industryCodeLevel2: "14",
		companyId: "156",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "VGT",
		companyName: "Công ty Cổ phần Tập đoàn Dệt May Việt Nam",
		industryId: "1229",
		industryCodeLevel3: "141",
		industryCodeLevel2: "14",
		companyId: "159",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HTO",
		companyName: "Công ty Cổ phần Dệt may Hòa Thọ",
		industryId: "1229",
		industryCodeLevel3: "141",
		industryCodeLevel2: "14",
		companyId: "160",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HHC",
		companyName: "Công ty Cổ phần Bánh kẹo Hải Hà",
		industryId: "1194",
		industryCodeLevel3: "107",
		industryCodeLevel2: "10",
		companyId: "161",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "BBC",
		companyName: "Công ty Cổ phần Bibica",
		industryId: "1194",
		industryCodeLevel3: "107",
		industryCodeLevel2: "10",
		companyId: "162",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "DLG",
		companyName: "Công ty Cổ phần Tập đoàn Đức Long Gia Lai",
		industryId: "1194",
		industryCodeLevel3: "107",
		industryCodeLevel2: "10",
		companyId: "163",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "SBT",
		companyName: "Công ty Cổ phần Thành Thành Công - Biên Hòa",
		industryId: "1194",
		industryCodeLevel3: "107",
		industryCodeLevel2: "10",
		companyId: "165",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "MSN",
		companyName: "Công ty Cổ phần Tập đoàn Masan",
		industryId: "1189",
		industryCodeLevel3: "106",
		industryCodeLevel2: "10",
		companyId: "168",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "LTG",
		companyName: "Công ty Cổ phần Tập đoàn Lộc Trời",
		industryId: "1189",
		industryCodeLevel3: "106",
		industryCodeLevel2: "10",
		companyId: "169",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "VNM",
		companyName: "Công ty Cổ phần Sữa Việt Nam",
		industryId: "1188",
		industryCodeLevel3: "105",
		industryCodeLevel2: "10",
		companyId: "170",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "IDP",
		companyName: "Công ty Cổ phần Sữa Quốc tế",
		industryId: "1188",
		industryCodeLevel3: "105",
		industryCodeLevel2: "10",
		companyId: "171",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "BVM",
		companyName: "Công ty Cổ phần Sữa Ba Vì",
		industryId: "1188",
		industryCodeLevel3: "105",
		industryCodeLevel2: "10",
		companyId: "172",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "MCM",
		companyName: "Công ty Cổ phần Sữa Mộc Châu",
		industryId: "1188",
		industryCodeLevel3: "105",
		industryCodeLevel2: "10",
		companyId: "173",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HNM",
		companyName: "Công ty Cổ phần Sữa Hà Nội",
		industryId: "1188",
		industryCodeLevel3: "105",
		industryCodeLevel2: "10",
		companyId: "174",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "AAM",
		companyName: "Công ty Cổ phần Thủy sản Mekong",
		industryId: "1177",
		industryCodeLevel3: "102",
		industryCodeLevel2: "10",
		companyId: "175",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "ACL",
		companyName: "Công ty Cổ phần Thủy sản Cửu Long",
		industryId: "1177",
		industryCodeLevel3: "102",
		industryCodeLevel2: "10",
		companyId: "176",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "MPC",
		companyName: "Công ty Cổ phần Tập đoàn Thủy sản Minh Phú",
		industryId: "1177",
		industryCodeLevel3: "102",
		industryCodeLevel2: "10",
		companyId: "177",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "ABT",
		companyName: "Công ty Cổ phần Thủy sản Bến Tre",
		industryId: "1177",
		industryCodeLevel3: "102",
		industryCodeLevel2: "10",
		companyId: "180",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "HVG",
		companyName: "Công ty Cổ phần Thủy sản Hùng Vương",
		industryId: "1177",
		industryCodeLevel3: "102",
		industryCodeLevel2: "10",
		companyId: "181",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "ANV",
		companyName: "Công ty Cổ phần Thủy sản Nam Việt",
		industryId: "1177",
		industryCodeLevel3: "102",
		industryCodeLevel2: "10",
		companyId: "182",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "VHC",
		companyName: "Công ty Cổ phần Thủy sản Vĩnh Hoàn",
		industryId: "1177",
		industryCodeLevel3: "102",
		industryCodeLevel2: "10",
		companyId: "183",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
	{
		"": "",
		companyCode: "MMVN",
		companyName: " MegaMarket Việt Nam",
		industryId: "1614",
		industryCodeLevel3: "474",
		industryCodeLevel2: "47",
		companyId: "184",
		yearFounded: "",
		mainAddress: "",
		phoneNumber: "",
		web: "",
		description: "",
		contactInfor: "",
		revenue: "",
		netIncome: "",
		partTimeEmployees: "",
		fullTimeEmployees: "",
	},
];
