module.exports = [
	{
		companyId: "",
		companyCode: "MWG",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "AEON",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "FRT",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "BTS",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "KHS",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "MWG",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "AEON",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "FRT",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "BTS",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "KHS",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "MWG",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "AEON",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "FRT",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "BTS",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "KHS",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "MWG",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "AEON",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "FRT",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "BTS",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "KHS",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "MWG",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "AEON",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "FRT",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "BTS",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "KHS",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "HSG",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "TTA",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "BVG",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "POM",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "TMS",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "HSG",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "TTA",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "BVG",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "POM",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "TMS",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "HSG",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "TTA",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "BVG",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "POM",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "TMS",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "HSG",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "TTA",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "BVG",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "POM",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "TMS",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "HSG",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "TTA",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "BVG",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "POM",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "TMS",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "MBS",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "KIS",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "VIX",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "ORS",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "TVB",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "MBS",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "KIS",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "VIX",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "ORS",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "TVB",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "MBS",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "KIS",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "VIX",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "ORS",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "TVB",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "MBS",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "KIS",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "VIX",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "ORS",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "TVB",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "MBS",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "KIS",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "VIX",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "ORS",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "",
		companyCode: "TVB",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
];
