module.exports = [
	{
		"": "",
		companyCode: "VIC",
		companyName: "Công ty Cổ phần Vingroup",
		industryId: "1907",
		industryCodeLevel3: "701",
	},
	{
		"": "",
		companyCode: "NVL",
		companyName: "Công ty Cổ phần Địa ốc No Va",
		industryId: "1890",
		industryCodeLevel3: "681",
	},
	{
		"": "",
		companyCode: "DXG",
		companyName: "Công ty Cổ phần Tập đoàn Đất Xanh",
		industryId: "1890",
		industryCodeLevel3: "681",
	},
	{
		"": "",
		companyCode: "FLC",
		companyName: "Công ty Cổ phần Tập đoàn FLC",
		industryId: "1890",
		industryCodeLevel3: "681",
	},
	{
		"": "",
		companyCode: "DXG",
		companyName: "Công ty Cổ phần Dịch vụ và Xây dựng Địa ốc Đất Xanh",
		industryId: "1890",
		industryCodeLevel3: "681",
	},
	{
		"": "",
		companyCode: "VCI",
		companyName: "Công ty Cổ phần Chứng khoán Bản Việt",
		industryId: "1879",
		industryCodeLevel3: "661",
	},
	{
		"": "",
		companyCode: "SSI",
		companyName: "Công ty Cổ phần Chứng khoán Sài Gòn",
		industryId: "1879",
		industryCodeLevel3: "661",
	},
	{
		"": "",
		companyCode: "VDS",
		companyName: "Công ty Cổ phần Chứng khoán Rồng Việt",
		industryId: "1879",
		industryCodeLevel3: "661",
	},
	{
		"": "",
		companyCode: "VND",
		companyName: "Công ty Cổ phần Chứng khoán VNDirect",
		industryId: "1879",
		industryCodeLevel3: "661",
	},
	{
		"": "",
		companyCode: "HCM",
		companyName: "Công ty Cổ phần Chứng khoán TP.HCM",
		industryId: "1879",
		industryCodeLevel3: "661",
	},
	{
		"": "",
		companyCode: "VIX",
		companyName: "Công ty Cổ phần Chứng khoán VIX",
		industryId: "1879",
		industryCodeLevel3: "661",
	},
	{
		"": "",
		companyCode: "ORS",
		companyName: "Công ty Cổ phần Chứng khoán Phương Đông",
		industryId: "1879",
		industryCodeLevel3: "661",
	},
	{
		"": "",
		companyCode: "TVB",
		companyName: "Công ty Cổ phần Chứng khoán Trí Việt",
		industryId: "1879",
		industryCodeLevel3: "661",
	},
	{
		"": "",
		companyCode: "MBS",
		companyName: "Công ty Cổ phần Chứng khoán MB",
		industryId: "1879",
		industryCodeLevel3: "661",
	},
	{
		"": "",
		companyCode: "KIS",
		companyName: "Công ty Cổ phần Chứng khoán KIS Việt Nam",
		industryId: "1879",
		industryCodeLevel3: "661",
	},
	{
		"": "",
		companyCode: "VNZ",
		companyName: "Công ty Cổ phần VNG",
		industryId: "1852",
		industryCodeLevel3: "631",
	},
	{
		"": "",
		companyCode: "FPT",
		companyName: "Công ty Cổ phần FPT",
		industryId: "1847",
		industryCodeLevel3: "620",
	},
	{
		"": "",
		companyCode: "PNJ",
		companyName: "Công ty Cổ phần Vàng bạc Đá quý Phú Nhuận (PNJ)",
		industryId: "1642",
		industryCodeLevel3: "477",
	},
	{
		"": "",
		companyCode: "DOJ",
		companyName: "Công ty Cổ phần Tập đoàn Vàng bạc Đá quý DOJI",
		industryId: "1642",
		industryCodeLevel3: "477",
	},
	{
		"": "",
		companyCode: "SJC",
		companyName: "Công ty Cổ phần Vàng bạc Đá quý SJC",
		industryId: "1642",
		industryCodeLevel3: "477",
	},
	{
		"": "",
		companyCode: "STC",
		companyName: "Công ty Cổ phần Sách và Thiết bị Trường học Hà Nội",
		industryId: "1637",
		industryCodeLevel3: "476",
	},
	{
		"": "",
		companyCode: "AFA",
		companyName: "Công ty Cổ phần Sách Alpha",
		industryId: "1637",
		industryCodeLevel3: "476",
	},
	{
		"": "",
		companyCode: "DUC",
		companyName: "Công ty Cổ phần Sách Đại học",
		industryId: "1637",
		industryCodeLevel3: "476",
	},
	{
		"": "",
		companyCode: "STP",
		companyName: "Công ty Cổ phần Sách và Thiết bị Trường học TP.HCM",
		industryId: "1637",
		industryCodeLevel3: "476",
	},
	{
		"": "",
		companyCode: "AEON",
		companyName: "Aeon Mall",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "B4B",
		companyName: "Metro AG",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "KRX004990",
		companyName: "Lotte",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "CRC",
		companyName: "Central Retail",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "WMT",
		companyName: "Walmart",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "BJC",
		companyName: "BJC Group",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "FRT",
		companyName: "Công ty Cổ phần Bán lẻ Kỹ thuật số FPT",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "MWG",
		companyName: "Công ty Cổ phần Thế Giới Di Động",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "VRE",
		companyName: "Công ty Cổ phần Thương mại Điện tử Bán lẻ Việt Nam",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "CGG",
		companyName: "Công ty Cổ phần Thương mại Dịch vụ Cổng Vàng",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "SAS",
		companyName: "Công ty Cổ phần Dịch vụ Tổng hợp Sài Gòn",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "VEC",
		companyName: "Công ty Cổ phần Thương mại Điện tử VinGroup",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "NBS",
		companyName: "Công ty Cổ phần Dịch vụ Tổng hợp Miền Bắc",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "VMG",
		companyName: "Công ty Cổ phần Thương mại Điện tử VinMart",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "VMS",
		companyName: "Công ty Cổ phần Thương mại Điện tử VinSmart",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "PYS",
		companyName: "Công ty Cổ phần Dịch vụ Tổng hợp Phú Yên",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "BNE",
		companyName: "Công ty Cổ phần Thương mại Điện tử Bắc Ninh",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "KHS",
		companyName: "Công ty Cổ phần Dịch vụ Tổng hợp Khánh Hòa",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "HTS",
		companyName: "Công ty Cổ phần Dịch vụ Tổng hợp Hà Tĩnh",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "BTS",
		companyName: "Công ty Cổ phần Dịch vụ Tổng hợp Bình Thuận",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "QBS",
		companyName: "Công ty Cổ phần Thương mại Điện tử Quảng Bình",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "DNS",
		companyName: "Công ty Cổ phần Thương mại Điện tử Đồng Nai",
		industryId: "1614",
		industryCodeLevel3: "474",
	},
	{
		"": "",
		companyCode: "VRE",
		companyName: "Công ty Cổ phần Vincom Retail",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "VCM",
		companyName: "Công ty Cổ phần Dịch vụ Bán lẻ Tổng hợp VinCommerce",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "PTC",
		companyName: "Công ty Cổ phần Tập đoàn Phú Thái",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "VCM",
		companyName: "Công ty Cổ phần Dịch vụ Thương mại VinCommerce",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "NKC",
		companyName: "Công ty Cổ phần Tập đoàn Nguyễn Kim",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "SAT",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Sài Gòn",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "HSM",
		companyName: "Công ty Cổ phần Siêu thị Hà Nội",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "HAT",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Hà Nội",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "QNS",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Quảng Ninh",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "MBM",
		companyName: "Công ty Cổ phần Siêu thị Miền Bắc",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "DNG",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Đà Nẵng",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "MTC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Miền Trung",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "BDC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Bình Dương",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "BET",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Bến Tre",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "NDC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Nam Định",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "HUE",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Huế",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "HPC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Hải Phòng",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "TBC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Thái Bình",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "VPC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Vĩnh Phúc",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "LDC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Lâm Đồng",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "HGC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Hậu Giang",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "PTC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Phú Thọ",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "LAC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Long An",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "TGC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Tiền Giang",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "CTC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Cần Thơ",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "AGC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp An Giang",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "STC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Sóc Trăng",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "TVC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Trà Vinh",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "BLC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Bạc Liêu",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "CMC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Cà Mau",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "KGC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Kiên Giang",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "HGC",
		companyName: "Công ty Cổ phần Thương mại Tổng hợp Hậu Giang",
		industryId: "1594",
		industryCodeLevel3: "471",
	},
	{
		"": "",
		companyCode: "DP3",
		companyName: "Công ty Cổ phần Dược phẩm Trung ương 3",
		industryId: "1536",
		industryCodeLevel3: "464",
	},
	{
		"": "",
		companyCode: "CTD",
		companyName: "Công ty Cổ phần Xây dựng Coteccons",
		industryId: "1457",
		industryCodeLevel3: "410",
	},
	{
		"": "",
		companyCode: "HBC",
		companyName: "Công ty Cổ phần Xây dựng Hòa Bình",
		industryId: "1457",
		industryCodeLevel3: "410",
	},
	{
		"": "",
		companyCode: "HBC",
		companyName: "Công ty Cổ phần Tập đoàn Xây dựng Hòa Bình",
		industryId: "1457",
		industryCodeLevel3: "410",
	},
	{
		"": "",
		companyCode: "BWE",
		companyName: "Công ty Cổ phần Đầu tư và Xây dựng Bình Dương",
		industryId: "1457",
		industryCodeLevel3: "410",
	},
	{
		"": "",
		companyCode: "PPC",
		companyName: "Công ty Cổ phần Nhiệt điện Phả Lại",
		industryId: "1418",
		industryCodeLevel3: "351",
	},
	{
		"": "",
		companyCode: "DQC",
		companyName: "Công ty Cổ phần Bóng đèn Điện Quang",
		industryId: "1353",
		industryCodeLevel3: "274",
	},
	{
		"": "",
		companyCode: "RAL",
		companyName: "Công ty Cổ phần Bóng đèn Phích nước Rạng Đông",
		industryId: "1353",
		industryCodeLevel3: "274",
	},
	{
		"": "",
		companyCode: "RAL",
		companyName: "Công ty Cổ phần Bóng đèn Phích nước Rạng Đông",
		industryId: "1353",
		industryCodeLevel3: "274",
	},
	{
		"": "",
		companyCode: "DQC",
		companyName: "Công ty Cổ phần Bóng đèn Điện Quang",
		industryId: "1353",
		industryCodeLevel3: "274",
	},
	{
		"": "",
		companyCode: "CEC",
		companyName: "Công ty Cổ phần Cơ điện Trần Phú",
		industryId: "1345",
		industryCodeLevel3: "271",
	},
	{
		"": "",
		companyCode: "BHE",
		companyName: "Công ty Cổ phần Điện tử Bình Hòa",
		industryId: "1345",
		industryCodeLevel3: "271",
	},
	{
		"": "",
		companyCode: "HPG",
		companyName: "Công ty Cổ phần Thép Hòa Phát",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "NKG",
		companyName: "Công ty Cổ phần Thép Nam Kim",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "HPG",
		companyName: "Công ty Cổ phần Tập đoàn Hòa Phát",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "TLH",
		companyName: "Công ty Cổ phần Thép Tiến Lên",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "VIS",
		companyName: "Công ty Cổ phần Thép Việt Ý",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "NKG",
		companyName: "Công ty Cổ phần Thép Nam Kim",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "HSG",
		companyName: "Công ty Cổ phần Tập đoàn Hoa Sen",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "POM",
		companyName: "Công ty Cổ phần Thép Pomina",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "TDS",
		companyName: "Công ty Cổ phần Thép Thủ Đức",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "BVG",
		companyName: "Công ty Cổ phần Thép Bắc Việt",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "TNB",
		companyName: "Công ty Cổ phần Thép Nhà Bè",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "TTA",
		companyName: "Công ty Cổ phần Thép Tân Tạo",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "PMT",
		companyName: "Công ty Cổ phần Thép Phú Mỹ",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "LBS",
		companyName: "Công ty Cổ phần Thép Long Biên",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "BHS",
		companyName: "Công ty Cổ phần Thép Biên Hòa",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "HAN",
		companyName: "Công ty Cổ phần Thép Hà Nội",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "SGN",
		companyName: "Công ty Cổ phần Thép Sài Gòn",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "DTL",
		companyName: "Công ty Cổ phần Thép Đại Thiên Lộc",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "HPG",
		companyName: "Công ty Cổ phần Sắt Thép Hòa Phát",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "POM",
		companyName: "Công ty Cổ phần Thép Pomina",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "TMS",
		companyName: "Công ty Cổ phần Sắt Thép Miền Nam",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "HPS",
		companyName: "Công ty Cổ phần Thép Hải Phòng",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "DNS",
		companyName: "Công ty Cổ phần Thép Đà Nẵng",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "PHS",
		companyName: "Công ty Cổ phần Thép Phú Mỹ",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "NTS",
		companyName: "Công ty Cổ phần Sắt Thép Nha Trang",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "QNS",
		companyName: "Công ty Cổ phần Thép Quy Nhơn",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "VDS",
		companyName: "Công ty Cổ phần Thép Việt Đức",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "VTS",
		companyName: "Công ty Cổ phần Thép Vũng Tàu",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "TNS",
		companyName: "Công ty Cổ phần Thép Thái Nguyên",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "LBS",
		companyName: "Công ty Cổ phần Thép Long Biên",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "CPS",
		companyName: "Công ty Cổ phần Thép Cẩm Phả",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "PTS",
		companyName: "Công ty Cổ phần Thép Phú Thọ",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "NDS",
		companyName: "Công ty Cổ phần Thép Nam Định",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "CDS",
		companyName: "Công ty Cổ phần Thép Cầu Diễn",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "HDS",
		companyName: "Công ty Cổ phần Thép Hà Đông",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "HDS",
		companyName: "Công ty Cổ phần Thép Hải Dương",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "HAG",
		companyName: "Công ty Cổ phần Thép Hoàng Anh Gia Lai",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "GSS",
		companyName: "Công ty Cổ phần Thép Gia Sàng",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "DAS",
		companyName: "Công ty Cổ phần Thép Đông Anh",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "HTS",
		companyName: "Công ty Cổ phần Thép Hoàng Thạch",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "MXS",
		companyName: "Công ty Cổ phần Thép Mỹ Xuân",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "TNS",
		companyName: "Công ty Cổ phần Thép Thống Nhất",
		industryId: "1313",
		industryCodeLevel3: "241",
	},
	{
		"": "",
		companyCode: "HT1",
		companyName: "Công ty Cổ phần Xi măng Hà Tiên 1",
		industryId: "1301",
		industryCodeLevel3: "239",
	},
	{
		"": "",
		companyCode: "HTV",
		companyName: "Công ty Cổ phần Xi măng Vicem Hoàng Thạch",
		industryId: "1301",
		industryCodeLevel3: "239",
	},
	{
		"": "",
		companyCode: "HT1",
		companyName: "Công ty Cổ phần Xi măng Hà Tiên 1",
		industryId: "1301",
		industryCodeLevel3: "239",
	},
	{
		"": "",
		companyCode: "BCC",
		companyName: "Công ty Cổ phần Xi măng Bỉm Sơn",
		industryId: "1301",
		industryCodeLevel3: "239",
	},
	{
		"": "",
		companyCode: "HOM",
		companyName: "Công ty Cổ phần Xi măng Vicem Hoàng Mai",
		industryId: "1301",
		industryCodeLevel3: "239",
	},
	{
		"": "",
		companyCode: "HVX",
		companyName: "Công ty Cổ phần Xi măng Vicem Hải Vân",
		industryId: "1301",
		industryCodeLevel3: "239",
	},
	{
		"": "",
		companyCode: "HLC",
		companyName: "Công ty Cổ phần Xi măng Hoàng Long",
		industryId: "1301",
		industryCodeLevel3: "239",
	},
	{
		"": "",
		companyCode: "HTV",
		companyName: "Công ty Cổ phần Xi măng Vicem Hà Tiên",
		industryId: "1301",
		industryCodeLevel3: "239",
	},
	{
		"": "",
		companyCode: "CLH",
		companyName: "Công ty Cổ phần Xi măng La Hiên",
		industryId: "1301",
		industryCodeLevel3: "239",
	},
	{
		"": "",
		companyCode: "BTS",
		companyName: "Công ty Cổ phần Xi măng Vicem Bút Sơn",
		industryId: "1301",
		industryCodeLevel3: "239",
	},
	{
		"": "",
		companyCode: "HPM",
		companyName: "Công ty Cổ phần Xi măng Hải Phòng",
		industryId: "1301",
		industryCodeLevel3: "239",
	},
	{
		"": "",
		companyCode: "BMP",
		companyName: "Công ty Cổ phần Nhựa Bình Minh",
		industryId: "1292",
		industryCodeLevel3: "222",
	},
	{
		"": "",
		companyCode: "NTP",
		companyName: "Công ty Cổ phần Nhựa Tiền Phong",
		industryId: "1292",
		industryCodeLevel3: "222",
	},
	{
		"": "",
		companyCode: "SRC",
		companyName: "Công ty Cổ phần Cao su Sao Vàng",
		industryId: "1289",
		industryCodeLevel3: "221",
	},
	{
		"": "",
		companyCode: "DRC",
		companyName: "Công ty Cổ phần Cao su Đà Nẵng",
		industryId: "1289",
		industryCodeLevel3: "221",
	},
	{
		"": "",
		companyCode: "DHG",
		companyName: "Công ty Cổ phần Dược Hậu Giang",
		industryId: "1285",
		industryCodeLevel3: "210",
	},
	{
		"": "",
		companyCode: "IMP",
		companyName: "Công ty Cổ phần Dược phẩm Imexpharm",
		industryId: "1285",
		industryCodeLevel3: "210",
	},
	{
		"": "",
		companyCode: "DGC",
		companyName: "Công ty Cổ phần Tập đoàn Hóa chất Đức Giang",
		industryId: "1274",
		industryCodeLevel3: "202",
	},
	{
		"": "",
		companyCode: "TNG",
		companyName: "Công ty Cổ phần Đầu tư và Thương mại TNG",
		industryId: "1229",
		industryCodeLevel3: "141",
	},
	{
		"": "",
		companyCode: "MSH",
		companyName: "Công ty Cổ phần May Sông Hồng",
		industryId: "1229",
		industryCodeLevel3: "141",
	},
	{
		"": "",
		companyCode: "VGG",
		companyName: "Công ty Cổ phần May Việt Tiến",
		industryId: "1229",
		industryCodeLevel3: "141",
	},
	{
		"": "",
		companyCode: "TCM",
		companyName: "Công ty Cổ phần Dệt may Thành Công",
		industryId: "1229",
		industryCodeLevel3: "141",
	},
	{
		"": "",
		companyCode: "M10",
		companyName: "Công ty Cổ phần May 10",
		industryId: "1229",
		industryCodeLevel3: "141",
	},
	{
		"": "",
		companyCode: "MNB",
		companyName: "Công ty Cổ phần May Nhà Bè",
		industryId: "1229",
		industryCodeLevel3: "141",
	},
	{
		"": "",
		companyCode: "VGG",
		companyName: "Công ty Cổ phần May Việt Tiến",
		industryId: "1229",
		industryCodeLevel3: "141",
	},
	{
		"": "",
		companyCode: "TCM",
		companyName: "Công ty Cổ phần Dệt may Thành Công",
		industryId: "1229",
		industryCodeLevel3: "141",
	},
	{
		"": "",
		companyCode: "VGT",
		companyName: "Công ty Cổ phần Tập đoàn Dệt May Việt Nam",
		industryId: "1229",
		industryCodeLevel3: "141",
	},
	{
		"": "",
		companyCode: "HTO",
		companyName: "Công ty Cổ phần Dệt may Hòa Thọ",
		industryId: "1229",
		industryCodeLevel3: "141",
	},
	{
		"": "",
		companyCode: "HHC",
		companyName: "Công ty Cổ phần Bánh kẹo Hải Hà",
		industryId: "1194",
		industryCodeLevel3: "107",
	},
	{
		"": "",
		companyCode: "BBC",
		companyName: "Công ty Cổ phần Bibica",
		industryId: "1194",
		industryCodeLevel3: "107",
	},
	{
		"": "",
		companyCode: "DLG",
		companyName: "Công ty Cổ phần Tập đoàn Đức Long Gia Lai",
		industryId: "1194",
		industryCodeLevel3: "107",
	},
	{
		"": "",
		companyCode: "BHS",
		companyName: "Công ty Cổ phần Đường Biên Hòa",
		industryId: "1194",
		industryCodeLevel3: "107",
	},
	{
		"": "",
		companyCode: "SBT",
		companyName: "Công ty Cổ phần Thành Thành Công - Biên Hòa",
		industryId: "1194",
		industryCodeLevel3: "107",
	},
	{
		"": "",
		companyCode: "QNS",
		companyName: "Công ty Cổ phần Đường Quảng Ngãi",
		industryId: "1194",
		industryCodeLevel3: "107",
	},
	{
		"": "",
		companyCode: "DLG",
		companyName: "Công ty Cổ phần Tập đoàn Đức Long Gia Lai",
		industryId: "1194",
		industryCodeLevel3: "107",
	},
	{
		"": "",
		companyCode: "MSN",
		companyName: "Công ty Cổ phần Tập đoàn Masan",
		industryId: "1189",
		industryCodeLevel3: "106",
	},
	{
		"": "",
		companyCode: "LTG",
		companyName: "Công ty Cổ phần Tập đoàn Lộc Trời",
		industryId: "1189",
		industryCodeLevel3: "106",
	},
	{
		"": "",
		companyCode: "VNM",
		companyName: "Công ty Cổ phần Sữa Việt Nam",
		industryId: "1188",
		industryCodeLevel3: "105",
	},
	{
		"": "",
		companyCode: "IDP",
		companyName: "Công ty Cổ phần Sữa Quốc tế",
		industryId: "1188",
		industryCodeLevel3: "105",
	},
	{
		"": "",
		companyCode: "BVM",
		companyName: "Công ty Cổ phần Sữa Ba Vì",
		industryId: "1188",
		industryCodeLevel3: "105",
	},
	{
		"": "",
		companyCode: "MCM",
		companyName: "Công ty Cổ phần Sữa Mộc Châu",
		industryId: "1188",
		industryCodeLevel3: "105",
	},
	{
		"": "",
		companyCode: "HNM",
		companyName: "Công ty Cổ phần Sữa Hà Nội",
		industryId: "1188",
		industryCodeLevel3: "105",
	},
	{
		"": "",
		companyCode: "AAM",
		companyName: "Công ty Cổ phần Thủy sản Mekong",
		industryId: "1177",
		industryCodeLevel3: "102",
	},
	{
		"": "",
		companyCode: "ACL",
		companyName: "Công ty Cổ phần Thủy sản Cửu Long",
		industryId: "1177",
		industryCodeLevel3: "102",
	},
	{
		"": "",
		companyCode: "MPC",
		companyName: "Công ty Cổ phần Tập đoàn Thủy sản Minh Phú",
		industryId: "1177",
		industryCodeLevel3: "102",
	},
	{
		"": "",
		companyCode: "ACL",
		companyName: "Công ty Cổ phần Thủy sản Cửu Long An Giang",
		industryId: "1177",
		industryCodeLevel3: "102",
	},
	{
		"": "",
		companyCode: "AAM",
		companyName: "Công ty Cổ phần Thủy sản Mekong",
		industryId: "1177",
		industryCodeLevel3: "102",
	},
	{
		"": "",
		companyCode: "ABT",
		companyName: "Công ty Cổ phần Thủy sản Bến Tre",
		industryId: "1177",
		industryCodeLevel3: "102",
	},
	{
		"": "",
		companyCode: "HVG",
		companyName: "Công ty Cổ phần Thủy sản Hùng Vương",
		industryId: "1177",
		industryCodeLevel3: "102",
	},
	{
		"": "",
		companyCode: "ANV",
		companyName: "Công ty Cổ phần Thủy sản Nam Việt",
		industryId: "1177",
		industryCodeLevel3: "102",
	},
	{
		"": "",
		companyCode: "VHC",
		companyName: "Công ty Cổ phần Thủy sản Vĩnh Hoàn",
		industryId: "1177",
		industryCodeLevel3: "102",
	},
];
