module.exports = [
	{
		companyId: "21",
		companyCode: "MWG",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "21",
		companyCode: "MWG",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "21",
		companyCode: "MWG",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "21",
		companyCode: "MWG",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "21",
		companyCode: "MWG",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "421",
		companyCode: "VCM",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "421",
		companyCode: "VCM",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "421",
		companyCode: "VCM",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "421",
		companyCode: "VCM",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "421",
		companyCode: "VCM",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "407",
		companyCode: "CGG",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "407",
		companyCode: "CGG",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "407",
		companyCode: "CGG",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "407",
		companyCode: "CGG",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "407",
		companyCode: "CGG",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "404",
		companyCode: "FRT",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "404",
		companyCode: "FRT",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "404",
		companyCode: "FRT",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "404",
		companyCode: "FRT",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "404",
		companyCode: "FRT",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "410",
		companyCode: "NBS",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "410",
		companyCode: "NBS",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "410",
		companyCode: "NBS",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "410",
		companyCode: "NBS",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "410",
		companyCode: "NBS",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "408",
		companyCode: "SAS",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "408",
		companyCode: "SAS",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "408",
		companyCode: "SAS",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "408",
		companyCode: "SAS",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "408",
		companyCode: "SAS",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "409",
		companyCode: "VEC",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "409",
		companyCode: "VEC",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "409",
		companyCode: "VEC",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "409",
		companyCode: "VEC",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "409",
		companyCode: "VEC",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "411",
		companyCode: "VMG",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "411",
		companyCode: "VMG",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "411",
		companyCode: "VMG",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "411",
		companyCode: "VMG",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "411",
		companyCode: "VMG",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "412",
		companyCode: "VMS",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "412",
		companyCode: "VMS",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "412",
		companyCode: "VMS",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "412",
		companyCode: "VMS",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "412",
		companyCode: "VMS",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "406",
		companyCode: "VRE",
		year: "2020",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "406",
		companyCode: "VRE",
		year: "2021",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "406",
		companyCode: "VRE",
		year: "2022",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "406",
		companyCode: "VRE",
		year: "2023",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
	{
		companyId: "406",
		companyCode: "VRE",
		year: "2024",
		environmentScore: "",
		socialScore: "",
		governanceScore: "",
		esgScore: "",
	},
];
