module.exports = [
	{
		criteriaCode: "1",
		companyCode: "MWG",
		criteriaId: "1",
		year: "2022",
		metricId: "1",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "1",
		companyCode: "MMVN",
		criteriaId: "1",
		year: "2022",
		metricId: "2",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "2",
		companyCode: "MWG",
		criteriaId: "2",
		year: "2022",
		metricId: "3",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "2",
		companyCode: "MMVN",
		criteriaId: "2",
		year: "2022",
		metricId: "4",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "3",
		companyCode: "MWG",
		criteriaId: "3",
		year: "2022",
		metricId: "5",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "3",
		companyCode: "MMVN",
		criteriaId: "3",
		year: "2022",
		metricId: "6",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "4",
		companyCode: "MWG",
		criteriaId: "4",
		year: "2022",
		metricId: "7",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "4",
		companyCode: "MMVN",
		criteriaId: "4",
		year: "2022",
		metricId: "8",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "9",
		companyCode: "MWG",
		criteriaId: "5",
		year: "2022",
		metricId: "9",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "9",
		companyCode: "MMVN",
		criteriaId: "5",
		year: "2022",
		metricId: "10",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "11",
		companyCode: "MWG",
		criteriaId: "6",
		year: "2022",
		metricId: "11",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "11",
		companyCode: "MMVN",
		criteriaId: "6",
		year: "2022",
		metricId: "12",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "12",
		companyCode: "MWG",
		criteriaId: "7",
		year: "2022",
		metricId: "13",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "12",
		companyCode: "MMVN",
		criteriaId: "7",
		year: "2022",
		metricId: "14",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "13",
		companyCode: "MWG",
		criteriaId: "8",
		year: "2022",
		metricId: "15",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "13",
		companyCode: "MMVN",
		criteriaId: "8",
		year: "2022",
		metricId: "16",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "15",
		companyCode: "MWG",
		criteriaId: "9",
		year: "2022",
		metricId: "17",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "15",
		companyCode: "MMVN",
		criteriaId: "9",
		year: "2022",
		metricId: "18",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "16",
		companyCode: "MWG",
		criteriaId: "10",
		year: "2022",
		metricId: "19",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "16",
		companyCode: "MMVN",
		criteriaId: "10",
		year: "2022",
		metricId: "20",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "17",
		companyCode: "MWG",
		criteriaId: "11",
		year: "2022",
		metricId: "21",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "17",
		companyCode: "MMVN",
		criteriaId: "11",
		year: "2022",
		metricId: "22",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "18",
		companyCode: "MWG",
		criteriaId: "12",
		year: "2022",
		metricId: "23",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "18",
		companyCode: "MMVN",
		criteriaId: "12",
		year: "2022",
		metricId: "24",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "21",
		companyCode: "MWG",
		criteriaId: "13",
		year: "2022",
		metricId: "25",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "21",
		companyCode: "MMVN",
		criteriaId: "13",
		year: "2022",
		metricId: "26",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "22",
		companyCode: "MWG",
		criteriaId: "14",
		year: "2022",
		metricId: "27",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "22",
		companyCode: "MMVN",
		criteriaId: "14",
		year: "2022",
		metricId: "28",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "23",
		companyCode: "MWG",
		criteriaId: "15",
		year: "2022",
		metricId: "29",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "23",
		companyCode: "MMVN",
		criteriaId: "15",
		year: "2022",
		metricId: "30",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "24",
		companyCode: "MWG",
		criteriaId: "16",
		year: "2022",
		metricId: "31",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "24",
		companyCode: "MMVN",
		criteriaId: "16",
		year: "2022",
		metricId: "32",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "25",
		companyCode: "MWG",
		criteriaId: "17",
		year: "2022",
		metricId: "33",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "25",
		companyCode: "MMVN",
		criteriaId: "17",
		year: "2022",
		metricId: "34",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "26",
		companyCode: "MWG",
		criteriaId: "18",
		year: "2022",
		metricId: "35",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "26",
		companyCode: "MMVN",
		criteriaId: "18",
		year: "2022",
		metricId: "36",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "32",
		companyCode: "MWG",
		criteriaId: "19",
		year: "2022",
		metricId: "37",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "32",
		companyCode: "MMVN",
		criteriaId: "19",
		year: "2022",
		metricId: "38",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "33",
		companyCode: "MWG",
		criteriaId: "22",
		year: "2022",
		metricId: "39",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "33",
		companyCode: "MMVN",
		criteriaId: "22",
		year: "2022",
		metricId: "40",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "34",
		companyCode: "MWG",
		criteriaId: "23",
		year: "2022",
		metricId: "41",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "34",
		companyCode: "MMVN",
		criteriaId: "23",
		year: "2022",
		metricId: "42",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "35",
		companyCode: "MWG",
		criteriaId: "24",
		year: "2022",
		metricId: "43",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "35",
		companyCode: "MMVN",
		criteriaId: "24",
		year: "2022",
		metricId: "44",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "36",
		companyCode: "MWG",
		criteriaId: "25",
		year: "2022",
		metricId: "45",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "36",
		companyCode: "MMVN",
		criteriaId: "25",
		year: "2022",
		metricId: "46",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "37",
		companyCode: "MWG",
		criteriaId: "26",
		year: "2022",
		metricId: "47",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "37",
		companyCode: "MMVN",
		criteriaId: "26",
		year: "2022",
		metricId: "48",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "38",
		companyCode: "MWG",
		criteriaId: "27",
		year: "2022",
		metricId: "49",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "38",
		companyCode: "MMVN",
		criteriaId: "27",
		year: "2022",
		metricId: "50",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "39",
		companyCode: "MWG",
		criteriaId: "28",
		year: "2022",
		metricId: "51",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "39",
		companyCode: "MMVN",
		criteriaId: "28",
		year: "2022",
		metricId: "52",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "40",
		companyCode: "MWG",
		criteriaId: "29",
		year: "2022",
		metricId: "53",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "40",
		companyCode: "MMVN",
		criteriaId: "29",
		year: "2022",
		metricId: "54",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "41",
		companyCode: "MWG",
		criteriaId: "30",
		year: "2022",
		metricId: "55",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "41",
		companyCode: "MMVN",
		criteriaId: "30",
		year: "2022",
		metricId: "56",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "42",
		companyCode: "MWG",
		criteriaId: "31",
		year: "2022",
		metricId: "57",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "42",
		companyCode: "MMVN",
		criteriaId: "31",
		year: "2022",
		metricId: "58",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "43",
		companyCode: "MWG",
		criteriaId: "32",
		year: "2022",
		metricId: "59",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "43",
		companyCode: "MMVN",
		criteriaId: "32",
		year: "2022",
		metricId: "60",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "44",
		companyCode: "MWG",
		criteriaId: "33",
		year: "2022",
		metricId: "61",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "44",
		companyCode: "MMVN",
		criteriaId: "33",
		year: "2022",
		metricId: "62",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "45",
		companyCode: "MWG",
		criteriaId: "34",
		year: "2022",
		metricId: "63",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "45",
		companyCode: "MMVN",
		criteriaId: "34",
		year: "2022",
		metricId: "64",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "47",
		companyCode: "MWG",
		criteriaId: "35",
		year: "2022",
		metricId: "65",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "47",
		companyCode: "MMVN",
		criteriaId: "35",
		year: "2022",
		metricId: "66",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "48",
		companyCode: "MWG",
		criteriaId: "36",
		year: "2022",
		metricId: "67",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "48",
		companyCode: "MMVN",
		criteriaId: "36",
		year: "2022",
		metricId: "68",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "49",
		companyCode: "MWG",
		criteriaId: "37",
		year: "2022",
		metricId: "69",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "49",
		companyCode: "MMVN",
		criteriaId: "37",
		year: "2022",
		metricId: "70",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "50",
		companyCode: "MWG",
		criteriaId: "38",
		year: "2022",
		metricId: "71",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "50",
		companyCode: "MMVN",
		criteriaId: "38",
		year: "2022",
		metricId: "72",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "51",
		companyCode: "MWG",
		criteriaId: "39",
		year: "2022",
		metricId: "73",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "51",
		companyCode: "MMVN",
		criteriaId: "39",
		year: "2022",
		metricId: "74",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "52",
		companyCode: "MWG",
		criteriaId: "40",
		year: "2022",
		metricId: "75",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "52",
		companyCode: "MMVN",
		criteriaId: "40",
		year: "2022",
		metricId: "76",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "53",
		companyCode: "MWG",
		criteriaId: "41",
		year: "2022",
		metricId: "77",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "53",
		companyCode: "MMVN",
		criteriaId: "41",
		year: "2022",
		metricId: "78",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "54",
		companyCode: "MWG",
		criteriaId: "42",
		year: "2022",
		metricId: "79",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "54",
		companyCode: "MMVN",
		criteriaId: "42",
		year: "2022",
		metricId: "80",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "55",
		companyCode: "MWG",
		criteriaId: "43",
		year: "2022",
		metricId: "81",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "55",
		companyCode: "MMVN",
		criteriaId: "43",
		year: "2022",
		metricId: "82",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "56",
		companyCode: "MWG",
		criteriaId: "44",
		year: "2022",
		metricId: "83",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "56",
		companyCode: "MMVN",
		criteriaId: "44",
		year: "2022",
		metricId: "84",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "57",
		companyCode: "MWG",
		criteriaId: "45",
		year: "2022",
		metricId: "85",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "57",
		companyCode: "MMVN",
		criteriaId: "45",
		year: "2022",
		metricId: "86",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "58",
		companyCode: "MWG",
		criteriaId: "46",
		year: "2022",
		metricId: "87",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "58",
		companyCode: "MMVN",
		criteriaId: "46",
		year: "2022",
		metricId: "88",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "61",
		companyCode: "MWG",
		criteriaId: "47",
		year: "2022",
		metricId: "89",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "61",
		companyCode: "MMVN",
		criteriaId: "47",
		year: "2022",
		metricId: "90",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "62",
		companyCode: "MWG",
		criteriaId: "48",
		year: "2022",
		metricId: "91",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "62",
		companyCode: "MMVN",
		criteriaId: "48",
		year: "2022",
		metricId: "92",
		score: "",
		pillarId: "2",
	},
	{
		criteriaCode: "63",
		companyCode: "MWG",
		criteriaId: "49",
		year: "2022",
		metricId: "93",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "63",
		companyCode: "MMVN",
		criteriaId: "49",
		year: "2022",
		metricId: "94",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "64",
		companyCode: "MWG",
		criteriaId: "50",
		year: "2022",
		metricId: "95",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "64",
		companyCode: "MMVN",
		criteriaId: "50",
		year: "2022",
		metricId: "96",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "66",
		companyCode: "MWG",
		criteriaId: "51",
		year: "2022",
		metricId: "97",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "66",
		companyCode: "MMVN",
		criteriaId: "51",
		year: "2022",
		metricId: "98",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "67",
		companyCode: "MWG",
		criteriaId: "52",
		year: "2022",
		metricId: "99",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "67",
		companyCode: "MMVN",
		criteriaId: "52",
		year: "2022",
		metricId: "100",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "68",
		companyCode: "MWG",
		criteriaId: "53",
		year: "2022",
		metricId: "101",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "68",
		companyCode: "MMVN",
		criteriaId: "53",
		year: "2022",
		metricId: "102",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "69",
		companyCode: "MWG",
		criteriaId: "54",
		year: "2022",
		metricId: "103",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "69",
		companyCode: "MMVN",
		criteriaId: "54",
		year: "2022",
		metricId: "104",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "70",
		companyCode: "MWG",
		criteriaId: "55",
		year: "2022",
		metricId: "105",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "70",
		companyCode: "MMVN",
		criteriaId: "55",
		year: "2022",
		metricId: "106",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "71",
		companyCode: "MWG",
		criteriaId: "56",
		year: "2022",
		metricId: "107",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "71",
		companyCode: "MMVN",
		criteriaId: "56",
		year: "2022",
		metricId: "108",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "72",
		companyCode: "MWG",
		criteriaId: "57",
		year: "2022",
		metricId: "109",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "72",
		companyCode: "MMVN",
		criteriaId: "57",
		year: "2022",
		metricId: "110",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "73",
		companyCode: "MWG",
		criteriaId: "58",
		year: "2022",
		metricId: "111",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "73",
		companyCode: "MMVN",
		criteriaId: "58",
		year: "2022",
		metricId: "112",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "74",
		companyCode: "MWG",
		criteriaId: "59",
		year: "2022",
		metricId: "113",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "74",
		companyCode: "MMVN",
		criteriaId: "59",
		year: "2022",
		metricId: "114",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "75",
		companyCode: "MWG",
		criteriaId: "60",
		year: "2022",
		metricId: "115",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "75",
		companyCode: "MMVN",
		criteriaId: "60",
		year: "2022",
		metricId: "116",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "76",
		companyCode: "MWG",
		criteriaId: "61",
		year: "2022",
		metricId: "117",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "76",
		companyCode: "MMVN",
		criteriaId: "61",
		year: "2022",
		metricId: "118",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "77",
		companyCode: "MWG",
		criteriaId: "62",
		year: "2022",
		metricId: "119",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "77",
		companyCode: "MMVN",
		criteriaId: "62",
		year: "2022",
		metricId: "120",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "78",
		companyCode: "MWG",
		criteriaId: "63",
		year: "2022",
		metricId: "121",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "78",
		companyCode: "MMVN",
		criteriaId: "63",
		year: "2022",
		metricId: "122",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "79",
		companyCode: "MWG",
		criteriaId: "64",
		year: "2022",
		metricId: "123",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "79",
		companyCode: "MMVN",
		criteriaId: "64",
		year: "2022",
		metricId: "124",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "80",
		companyCode: "MWG",
		criteriaId: "65",
		year: "2022",
		metricId: "125",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "80",
		companyCode: "MMVN",
		criteriaId: "65",
		year: "2022",
		metricId: "126",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "81",
		companyCode: "MWG",
		criteriaId: "66",
		year: "2022",
		metricId: "127",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "81",
		companyCode: "MMVN",
		criteriaId: "66",
		year: "2022",
		metricId: "128",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "82",
		companyCode: "MWG",
		criteriaId: "67",
		year: "2022",
		metricId: "129",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "82",
		companyCode: "MMVN",
		criteriaId: "67",
		year: "2022",
		metricId: "130",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "83",
		companyCode: "MWG",
		criteriaId: "68",
		year: "2022",
		metricId: "131",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "83",
		companyCode: "MMVN",
		criteriaId: "68",
		year: "2022",
		metricId: "132",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "84",
		companyCode: "MWG",
		criteriaId: "69",
		year: "2022",
		metricId: "133",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "84",
		companyCode: "MMVN",
		criteriaId: "69",
		year: "2022",
		metricId: "134",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "85",
		companyCode: "MWG",
		criteriaId: "70",
		year: "2022",
		metricId: "135",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "85",
		companyCode: "MMVN",
		criteriaId: "70",
		year: "2022",
		metricId: "136",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "86",
		companyCode: "MWG",
		criteriaId: "71",
		year: "2022",
		metricId: "137",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "86",
		companyCode: "MMVN",
		criteriaId: "71",
		year: "2022",
		metricId: "138",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "88",
		companyCode: "MWG",
		criteriaId: "72",
		year: "2022",
		metricId: "139",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "88",
		companyCode: "MMVN",
		criteriaId: "72",
		year: "2022",
		metricId: "140",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "89",
		companyCode: "MWG",
		criteriaId: "73",
		year: "2022",
		metricId: "141",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "89",
		companyCode: "MMVN",
		criteriaId: "73",
		year: "2022",
		metricId: "142",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "90",
		companyCode: "MWG",
		criteriaId: "74",
		year: "2022",
		metricId: "143",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "90",
		companyCode: "MMVN",
		criteriaId: "74",
		year: "2022",
		metricId: "144",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "91",
		companyCode: "MWG",
		criteriaId: "75",
		year: "2022",
		metricId: "145",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "91",
		companyCode: "MMVN",
		criteriaId: "75",
		year: "2022",
		metricId: "146",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "92",
		companyCode: "MWG",
		criteriaId: "76",
		year: "2022",
		metricId: "147",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "92",
		companyCode: "MMVN",
		criteriaId: "76",
		year: "2022",
		metricId: "148",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "93",
		companyCode: "MWG",
		criteriaId: "77",
		year: "2022",
		metricId: "149",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "93",
		companyCode: "MMVN",
		criteriaId: "77",
		year: "2022",
		metricId: "150",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "100",
		companyCode: "MWG",
		criteriaId: "20",
		year: "2022",
		metricId: "151",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "100",
		companyCode: "MMVN",
		criteriaId: "20",
		year: "2022",
		metricId: "152",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "101",
		companyCode: "MWG",
		criteriaId: "21",
		year: "2022",
		metricId: "153",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "101",
		companyCode: "MMVN",
		criteriaId: "21",
		year: "2022",
		metricId: "154",
		score: "",
		pillarId: "1",
	},
	{
		criteriaCode: "102",
		companyCode: "MWG",
		criteriaId: "78",
		year: "2022",
		metricId: "155",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "102",
		companyCode: "MMVN",
		criteriaId: "78",
		year: "2022",
		metricId: "156",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "103",
		companyCode: "MWG",
		criteriaId: "79",
		year: "2022",
		metricId: "157",
		score: "",
		pillarId: "3",
	},
	{
		criteriaCode: "103",
		companyCode: "MMVN",
		criteriaId: "79",
		year: "2022",
		metricId: "158",
		score: "",
		pillarId: "3",
	},
];
