module.exports = [
	{
		criteriaId: "1",
		criteriaCode: "1",
		name: "Khối lượng rác thải hữu cơ/ doanh thu",
		dataType: "Số",
		description: "",
		pillarId: "1",
		categoryId: "1",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01336254",
		unit: "Tấn/ Triệu đồng",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "2",
		criteriaCode: "2",
		name: "Khối lượng rác thải vô cơ/ Doanh thu",
		dataType: "Số",
		description: "",
		pillarId: "1",
		categoryId: "1",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.02030433",
		unit: "Tấn/ Triệu đồng",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "3",
		criteriaCode: "3",
		name: "Khối lượng rác thải có thể tái chế/ Doanh thu",
		dataType: "Số",
		description: "",
		pillarId: "1",
		categoryId: "1",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00896682",
		unit: "Tấn/ Triệu đồng",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "4",
		criteriaCode: "4",
		name: "Tỷ lệ sử dụng bao bì có thể tái chế",
		dataType: "Phần trăm",
		description: "",
		pillarId: "1",
		categoryId: "1",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00027139",
		unit: "%",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "5",
		criteriaCode: "9",
		name: "Tỷ lệ rác thải được xử lý đặc biệt",
		dataType: "Phần trăm",
		description: "",
		pillarId: "1",
		categoryId: "1",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01615298",
		unit: "%",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "6",
		criteriaCode: "11",
		name: "Doanh nghiệp có quy định về việc phân loại rác thải tại nguồn không?",
		dataType: "Boolean",
		description: "",
		pillarId: "1",
		categoryId: "1",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01153919",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "7",
		criteriaCode: "12",
		name: "Lượng nước doanh nghiệp tiêu thụ/ Doanh thu",
		dataType: "Số",
		description: "",
		pillarId: "1",
		categoryId: "2",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.02069036",
		unit: "Mét khối/ Triệu đồng",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "8",
		criteriaCode: "13",
		name: "Tỷ lệ nước được tái chế",
		dataType: "Phần trăm",
		description: "",
		pillarId: "1",
		categoryId: "2",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.0204304",
		unit: "%",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "9",
		criteriaCode: "15",
		name: "Lượng điện tiêu thụ/ Doanh thu",
		dataType: "Số",
		description: "",
		pillarId: "1",
		categoryId: "2",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01998716",
		unit: "Mwh/ Triệu đồng",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "10",
		criteriaCode: "16",
		name: "Tỷ lệ điện năng được sử dụng từ nguồn năng lượng tái tạo",
		dataType: "Phần trăm",
		description: "",
		pillarId: "1",
		categoryId: "2",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01005988",
		unit: "%",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "11",
		criteriaCode: "17",
		name: "Khối lượng giấy tiêu thụ/ Doanh thu",
		dataType: "Số",
		description: "",
		pillarId: "1",
		categoryId: "2",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01678086",
		unit: "kg/ Triệu đồng",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "12",
		criteriaCode: "18",
		name: "Lượng mực in tiêu thụ/ Doanh thu",
		dataType: "Số",
		description: "",
		pillarId: "1",
		categoryId: "2",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.0223885",
		unit: "kg/ triệu đồng",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "13",
		criteriaCode: "21",
		name: "Lượng phát thải từ các thiết bị làm lạnh/ Doanh thu",
		dataType: "Số",
		description: "",
		pillarId: "1",
		categoryId: "3",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00334646",
		unit: "kg GhG/ Triệu đồng",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "14",
		criteriaCode: "22",
		name: "Mức chi tiêu của doanh nghiệp cho các vấn đề môi trường/ Doanh thu",
		dataType: "Số",
		description: "",
		pillarId: "1",
		categoryId: "4",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01351989",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "15",
		criteriaCode: "23",
		name: "Mức tiêu thụ điện/ Từng cửa hàng",
		dataType: "Số",
		description: "",
		pillarId: "1",
		categoryId: "2",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01080476",
		unit: "Mwh/ Cửa hàng",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "16",
		criteriaCode: "24",
		name: "Mức tiêu thụ nước/ Từng cửa hàng",
		dataType: "Số",
		description: "",
		pillarId: "1",
		categoryId: "2",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01922958",
		unit: "Mét khối/ Cửa hàng",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "17",
		criteriaCode: "25",
		name: "Lượng phát thải khí nhà kính phạm vi 1/ Doanh thu",
		dataType: "Số",
		description: "",
		pillarId: "1",
		categoryId: "3",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01641644",
		unit: "Tấn CO2/ Triệu đồng",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "18",
		criteriaCode: "26",
		name: "Lượng phát thải khí nhà kính phạm vi 2/ Doanh thu",
		dataType: "Số",
		description: "",
		pillarId: "1",
		categoryId: "3",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00597014",
		unit: "Tấn CO2/ Triệu đồng",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "19",
		criteriaCode: "32",
		name: "Trong năm trước, doanh nghiệp có đánh giá và giám sát các hoạt động của doanh nghiệp mà có tác động đáng kể đến đa dạng sinh học không?",
		dataType: "Số",
		description: "",
		pillarId: "1",
		categoryId: "5",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00851125",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "20",
		criteriaCode: "100",
		name: "Mức tiêu thụ điện/ Từng chi nhánh",
		dataType: "Số",
		description: "",
		pillarId: "1",
		categoryId: "2",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.02171966",
		unit: "Mwh/ Chi nhánh",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "21",
		criteriaCode: "101",
		name: "Mức tiêu thụ nước/ Từng chi nhánh",
		dataType: "Số",
		description: "",
		pillarId: "1",
		categoryId: "2",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00108999",
		unit: "Mét khối/ Chi nhánh",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "22",
		criteriaCode: "33",
		name: "Mức chi tiêu của doanh nghiệp dành cho các hoạt động xã hội/ Tổng doanh thu",
		dataType: "Số",
		description: "",
		pillarId: "2",
		categoryId: "6",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00778279",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "23",
		criteriaCode: "34",
		name: "Số hoạt động xã hội trung bình mà 1 nhân viên tham gia/ năm",
		dataType: "Số",
		description: "",
		pillarId: "2",
		categoryId: "6",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01801165",
		unit: "Hoạt động/ Người",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "24",
		criteriaCode: "35",
		name: "Thành quả của các hoạt động xã hội về con người/ Tổng số nhân viên",
		dataType: "Số",
		description: "",
		pillarId: "2",
		categoryId: "6",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01959754",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "25",
		criteriaCode: "36",
		name: "Thành quả của các hoạt động xã hội về cơ sở vật chất/ Tổng số nhân viên",
		dataType: "Số",
		description: "",
		pillarId: "2",
		categoryId: "6",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00850632",
		unit: "Cơ sở vật chất/ người",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "26",
		criteriaCode: "37",
		name: "Thành quả của các hoạt động xã hội về tiền và các khoản tương đương có thể quy đổi ra tiền mặt/ Tổng số nhân viên",
		dataType: "Số",
		description: "",
		pillarId: "2",
		categoryId: "6",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01168052",
		unit: "Triệu đồng/ người",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "27",
		criteriaCode: "38",
		name: "Tỷ lệ người lao động tham gia công đoàn",
		dataType: "Phần trăm",
		description: "",
		pillarId: "2",
		categoryId: "7",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00585051",
		unit: "%",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "28",
		criteriaCode: "39",
		name: "Mức chênh lệch lương theo giới tính ở cấp bậc C-level",
		dataType: "Phần trăm",
		description: "",
		pillarId: "2",
		categoryId: "8",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.02036158",
		unit: "%",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "29",
		criteriaCode: "40",
		name: "Mức chênh lệch lương theo giới tính ở cấp bậc trưởng dự án, trưởng phòng,...",
		dataType: "Phần trăm",
		description: "",
		pillarId: "2",
		categoryId: "8",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00027515",
		unit: "%",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "30",
		criteriaCode: "41",
		name: "Mức chênh lệch lương theo giới tính ở cấp bậc nhân viên",
		dataType: "Phần trăm",
		description: "",
		pillarId: "2",
		categoryId: "8",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01557468",
		unit: "%",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "31",
		criteriaCode: "42",
		name: "Tỷ lệ tai nạn lao động của doanh nghiệp",
		dataType: "Phần trăm",
		description: "",
		pillarId: "2",
		categoryId: "7",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01813989",
		unit: "%",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "32",
		criteriaCode: "43",
		name: "Tỷ lệ tử vong do nghề nghiệp của doanh nghiệp",
		dataType: "Phần trăm",
		description: "",
		pillarId: "2",
		categoryId: "7",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00906771",
		unit: "%",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "33",
		criteriaCode: "44",
		name: "Tỷ lệ người lao động mắc bệnh nghề nghiệp trong doanh nghiệp",
		dataType: "Phần trăm",
		description: "",
		pillarId: "2",
		categoryId: "7",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01495053",
		unit: "%",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "34",
		criteriaCode: "45",
		name: "Điểm hài lòng trung bình của nhân viên đối với công ty",
		dataType: "Số",
		description: "",
		pillarId: "2",
		categoryId: "7",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01826523",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "35",
		criteriaCode: "47",
		name: "Mức chi tiêu của doanh nghiệp dành cho đào tạo nhân viên/  Tổng doanh thu",
		dataType: "Số",
		description: "",
		pillarId: "2",
		categoryId: "8",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00315631",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "36",
		criteriaCode: "48",
		name: "Tổng số giờ đào tạo nhân viên/ tổng số nhân viên",
		dataType: "Số",
		description: "",
		pillarId: "2",
		categoryId: "8",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01554957",
		unit: "Giờ/ Người",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "37",
		criteriaCode: "49",
		name: "Tỷ lệ nhân viên được đào tạo thêm mỗi năm",
		dataType: "Phần trăm",
		description: "",
		pillarId: "2",
		categoryId: "8",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01409146",
		unit: "%",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "38",
		criteriaCode: "50",
		name: "Tỷ lệ giới tính ở cấp bậc C-level",
		dataType: "Phần trăm",
		description: "",
		pillarId: "2",
		categoryId: "7",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00643222",
		unit: "%",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "39",
		criteriaCode: "51",
		name: "Tỷ lệ giới tính ở cấp bậc trưởng dự án, trưởng phòng,...",
		dataType: "Phần trăm",
		description: "",
		pillarId: "2",
		categoryId: "7",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00436484",
		unit: "%",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "40",
		criteriaCode: "52",
		name: "Tỷ lệ giới tính ở cấp bậc nhân viên",
		dataType: "Phần trăm",
		description: "",
		pillarId: "2",
		categoryId: "7",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00678984",
		unit: "%",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "41",
		criteriaCode: "53",
		name: "Tỷ lệ nhân viên là người nước ngoài của doanh nghiệp",
		dataType: "Phần trăm",
		description: "",
		pillarId: "2",
		categoryId: "7",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.02014677",
		unit: "%",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "42",
		criteriaCode: "54",
		name: "Tỷ lệ nhân viên được tuyển mới mỗi năm",
		dataType: "Phần trăm",
		description: "",
		pillarId: "2",
		categoryId: "7",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00333511",
		unit: "%",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "43",
		criteriaCode: "55",
		name: "Tỷ lệ nhân viên bị khuyết tật của doanh nghiệp",
		dataType: "Phần trăm",
		description: "",
		pillarId: "2",
		categoryId: "7",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.02183834",
		unit: "%",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "44",
		criteriaCode: "56",
		name: "Doanh nghiệp có tuân thủ tiêu chuẩn OHSAS 18001 hoặc UNI EN ISO 45001 về sức khoẻ và an toàn nghề nghiệp của nhân viên không?",
		dataType: "Boolean",
		description: "",
		pillarId: "2",
		categoryId: "7",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01539916",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "45",
		criteriaCode: "57",
		name: "Doanh nghiệp có tuân thủ tiêu chuẩn ISO 26000 về trách nhiệm xã hội không",
		dataType: "Boolean",
		description: "",
		pillarId: "2",
		categoryId: "6",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00673322",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "46",
		criteriaCode: "58",
		name: "Doanh nghiệp có trao đổi với các bên liên quan trong chuỗi cung ứng về vấn đề kiểm soát sử dụng lao động trẻ em thường xuyên không?",
		dataType: "Boolean",
		description: "",
		pillarId: "2",
		categoryId: "9",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01540636",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "47",
		criteriaCode: "61",
		name: "Mức chênh lệch giữa mức lương tổi thiểu so với mức lương tối thiểu của vùng là bao nhiêu",
		dataType: "Phần trăm",
		description: "",
		pillarId: "2",
		categoryId: "9",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.0015195",
		unit: "%",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "48",
		criteriaCode: "62",
		name: "Tổng mức chi tiêu dành cho hệ thống bảo mật thông tin/ Tổng doanh thu",
		dataType: "Phần trăm",
		description: "",
		pillarId: "2",
		categoryId: "10",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.02075939",
		unit: "%",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "49",
		criteriaCode: "63",
		name: "Tỷ lệ chênh lệch giới tính của HĐQT (Nữ so với Nam)",
		dataType: "Phần trăm",
		description: "",
		pillarId: "3",
		categoryId: "7",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01689897",
		unit: "%",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "50",
		criteriaCode: "64",
		name: "Tỷ lệ số nhà cung ứng được đánh giá qua các năm",
		dataType: "Phần trăm",
		description: "",
		pillarId: "3",
		categoryId: "12",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00367462",
		unit: "%",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "51",
		criteriaCode: "66",
		name: "Trong trường hợp doanh nghiệp bắt buộc phải có Kiểm toán độc lập theo pháp luật Việt Nam, doanh nghiệp có công bố đã bổ nhiệm một bên độc lập (kiểm tra, giám sát viên) là Kiểm toán độc lập",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "11",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.02015177",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "52",
		criteriaCode: "67",
		name: "Tổng số trường hợp vi phạm hành chính của doanh nghiệp",
		dataType: "Số",
		description: "",
		pillarId: "3",
		categoryId: "15",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00554831",
		unit: "Vụ",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "53",
		criteriaCode: "68",
		name: "Doanh nghiệp có chính sách phát triển bền vững rõ ràng và cam kết thực hiện các chính sách và hoạt động hướng đến phát triển bền vững không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "13",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01375874",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "54",
		criteriaCode: "69",
		name: "Doanh nghiệp đã đạt được chứng nhận ISO 37001 về hệ thống quản lý chống hối lộ chưa?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "15",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01984252",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "55",
		criteriaCode: "70",
		name: "Cơ cấu HĐQT hoặc HĐTV hoặc ban Giám đốc có đa dạng về kiến thức và kinh nghiệm về pháp luật, tài chính, lĩnh vực hoạt động kinh doanh của doanh nghiệp không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "11",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00583078",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "56",
		criteriaCode: "71",
		name: "Trong năm trước, doanh nghiệp có thường xuyên cập nhật các nội dung trên website doanh nghiệp và bảo đảm mọi thông tin được cập nhật đều bằng cả tiếng Việt và tiếng Anh không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "12",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00804452",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "57",
		criteriaCode: "72",
		name: "Trong năm trước, tiền lương của người điều hành hoạt động kinh doanh (Giám đốc, Tổng giám đốc, v.v) có được thể hiện thành mục riêng trong Báo cáo tài chính hàng năm của doanh nghiệp và được công khai hoặc báo cáo Đại hội đồng cổ đông, hoặc Ban giám đốc tại cuộc họp thường niên không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "12",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01022989",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "58",
		criteriaCode: "73",
		name: " Báo cáo thường niên có quy chế rõ rảng về lương, thưởng, các khoản thu nhập khác, quỹ phúc lợi và chi phí mà doanh nghiệp chi trả, thanh toán cho từng thành viên trong HĐQT hoặc HĐTV hoặc Ban Giám đốc không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "11",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00182145",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "59",
		criteriaCode: "74",
		name: "Báo cáo thường niên có công bố phát biểu, tuyên bố khẳng định sự tuân thủ đầy đủ của doanh nghiệp với các quy tắc quản trị doanh nghiệp và trong trường hợp có việc không tuân thủ, báo cáo có nếu rõ và giải thích lý do cho mỗi vấn đề đó không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "15",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00011111",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "60",
		criteriaCode: "75",
		name: "Doanh nghiệp niêm yết có thành lập các tiểu ban sau: tiểu ban chính sách phát triển, tiểu ban nhân sự, tiểu ban lương thưởng hay các đơn vị tương đương không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "11",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01682025",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "61",
		criteriaCode: "76",
		name: "Trong năm gần nhất, tỷ lệ tiểu ban trực thuộc Hội đồng quản trị do Thành viên độc lập làm trưởng ban là bao nhiêu?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "11",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00878323",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "62",
		criteriaCode: "77",
		name: " Doanh nghiệp có đảm bảo tối thiểu 20% tổng số thành viên của HĐQT là thành viên độc lập không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "11",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.0129975",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "63",
		criteriaCode: "78",
		name: "Trong năm trước, báo cáo đánh giá về hoạt động của HĐQT có phải do thành viên độc lập đánh giá không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "11",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01299667",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "64",
		criteriaCode: "79",
		name: " Doanh nghiệp có thành lập bộ phận Kiểm toán nội bộ không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "11",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.02196712",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "65",
		criteriaCode: "80",
		name: "Trong trường hợp doanh nghiệp bắt buộc phải có Kiểm toán nội bộ theo pháp luật Việt Nam, danh sách các ứng viên kiểm toán có được công bố công khai không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "11",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01950667",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "66",
		criteriaCode: "81",
		name: " Trong trường hợp doanh nghiệp bắt buộc phải có Ban Kiểm soát theo pháp luật Việt Nam, doanh nghiệp có thành lập Ban Kiểm soát không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "11",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00388906",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "67",
		criteriaCode: "82",
		name: "Trong năm qua, chủ tịch Ủy ban kiểm toán có phải là Thành viên độc lập HĐQT không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "11",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01577522",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "68",
		criteriaCode: "83",
		name: "Doanh nghiệp có thành lập Ủy ban Quản lý rủi ro không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "11",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.02112524",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "69",
		criteriaCode: "84",
		name: " Chủ tịch Ủy ban Quản lý rủi ro có phải là thành viên độc lập HĐQT không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "11",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01893822",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "70",
		criteriaCode: "85",
		name: "Doanh nghiệp có bộ phận chịu trách nhiệm giám sát truyền thông ra bên ngoài và lưu trữ thông tin theo quy định của pháp luật không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "12",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.0154536",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "71",
		criteriaCode: "86",
		name: "Trong năm trước, doanh nghiệp có công bố tính độc lập của thành viên HĐQT không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "11",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01759226",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "72",
		criteriaCode: "88",
		name: "Trong năm trước, tài liệu họp Đại Hội Đồng Cổ Đông có cung cấp thông tin về các ứng viên Hội đồng quản trị và Ban Kiểm Soát (nếu có) tối thiểu 10 ngày trước ngày khai mạc đại hội không",
		dataType: "Số",
		description: "",
		pillarId: "3",
		categoryId: "12",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00727491",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "73",
		criteriaCode: "89",
		name: "Trong thư mời tham dự Đại Hội Đồng Cổ Đông, cổ đông có được hướng dẫn để đóng góp ý kiến trong thời gian trước ngày tham dự đại hội về (các) vấn đề thảo luận trong chương trình nghị sự của Đại Hội Đồng Cổ Đông không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "12",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01786737",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "74",
		criteriaCode: "90",
		name: "Trong năm trước, doanh nghiệp có công bố và sử dụng tài liệu họp, biên bản họp, nghị quyết Đại Hội Đồng Cổ Đông bằng tiếng Việt và tiếng Anh?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "12",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01761317",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "75",
		criteriaCode: "91",
		name: "Doanh nghiệp có xây dựng và công bố chính sách liên quan đến việc khiếu nại của cổ đông không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "12",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.02183511",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "76",
		criteriaCode: "92",
		name: "Trong năm trước, đại hội đồng cổ đông có thông qua thù lao hoặc lương thưởng, chi phí, các khoản lợi ích do doanh nghiệp thanh toán cho từng thành viên Hội đồng Quản trị không?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "12",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.0077805",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "77",
		criteriaCode: "93",
		name: "Doanh nghiệp có thực hiện chi trả cổ tức đầy đủ trong thời hạn 06 tháng, kể từ ngày kết thúc họp Đại hội đồng cổ đông thường niên?",
		dataType: "Boolean",
		description: "",
		pillarId: "3",
		categoryId: "14",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.01918196",
		unit: "",
		polarityIndicating: "positive",
		pillarWeight: "",
	},
	{
		criteriaId: "78",
		criteriaCode: "102",
		name: "Tổng số trường hợp vi phạm bị kỷ luật của doanh nghiệp",
		dataType: "Số",
		description: "",
		pillarId: "3",
		categoryId: "15",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00291753",
		unit: "Vụ",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
	{
		criteriaId: "79",
		criteriaCode: "103",
		name: "Tổng số trường hợp vi phạm hình sự của doanh nghiệp",
		dataType: "Số",
		description: "",
		pillarId: "3",
		categoryId: "15",
		measurementMethod: "",
		applicableIndustryCode: "474",
		transformationMethod: "percentile ranking",
		weight: "0.00864298",
		unit: "Vụ",
		polarityIndicating: "negative",
		pillarWeight: "",
	},
];
