module.exports = [
	{
		questionCode: "AS197",
		answer: "Doanh nghiệp không nhận xác minh từ bên thứ ba cho lượng khí thải phạm vi 1 và 2 hoặc công bố công khai kết quả.",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS197",
		answer: "Doanh nghiệp nhận xác minh từ bên thứ ba cho một phần lượng khí thải phạm vi 1 và 2 và công bố kết quả công khai. Việc xác minh bên thứ ba được thực hiện ở mức độ đảm bảo hạn chế.",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS197",
		answer: "Doanh nghiệp nhận xác minh đầy đủ từ bên thứ ba cho tất cả lượng khí thải phạm vi 1 và 2 và công bố công khai kết quả. Việc xác minh bên thứ ba được thực hiện ở mức độ đảm bảo hạn chế.",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS197",
		answer: "Doanh nghiệp nhận xác minh từ bên thứ ba cho tất cả lượng khí thải phạm vi 1 và 2 và công bố công khai kết quả. Việc xác minh từ bên thứ ba được thực hiện ở mức độ đảm bảo hợp lý, tốt nhất là từ một Doanh nghiệp xác minh được công nhận.",
		dummy: "3",
		language: "vi",
	},
	{
		questionCode: "AS196",
		answer: "Doanh nghiệp không theo dõi và công bố công khai mức sử dụng năng lượng",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS196",
		answer: "Doanh nghiệp theo dõi và công cố công khai các nguồn năng lượng chính",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS196",
		answer: "Doanh nghiệp theo dõi và công bố công khai tất cả mức sử dụng năng lượng và đã tạo ra quy trình hàng năm để tiếp tục theo dõi mức sử dụng năng lượng",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS196",
		answer: "Doanh nghiệp đã theo dõi và công bố công khai tất cả mức sử dụng năng lượng trong ít nhất 5 năm và đã tạo ra quy trình hàng năm để tiếp tục theo dõi mức sử dụng năng lượng",
		dummy: "3",
		language: "vi",
	},
	{
		questionCode: "AS195",
		answer: "Doanh nghiệp không tính toán và công bố công khai bất kỳ lượng khí thải phạm vi 1 hoặc phạm vi 2 nào",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS195",
		answer: "Doanh nghiệp tính toán và công bố công khai tất cả các nguồn phát thải chính của phạm vi 1 và phạm vi 2",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS195",
		answer: "Doanh nghiệp tính toán và công bố công khai tất cả lượng phát thải phạm vi 1 và phạm vi 2. Doanh nghiệp đã tạo quy trình hàng năm để tiếp tục công bố lượn khí thải phạm vi 1 và 2",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS195",
		answer: "Doanh nghiệp đã tính toán và công bố công khai tất cả lượng khí thải phạm vi 1 và phạm vi 2 trong ít nhất 5 năm và đã tạo ra quy trình hàng năm và tiếp tục công bố lượng khí thải phạm vi 1 và 2",
		dummy: "3",
		language: "vi",
	},
	{
		questionCode: "AS192",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS192",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS184",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS184",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS178",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS178",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS176",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS176",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS175",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS175",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS174",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS174",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS173",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS173",
		answer: "Có",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS173",
		answer: "Không áp dụng do pháp luật Việt Nam không yêu cầu",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS169",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS169",
		answer: "Có - Bằng tiếng Việt",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS169",
		answer: "Có - Bằng tiếng Anh",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS169",
		answer: "Có - Bằng cả tiếng Việt và tiếng Anh",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS168",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS168",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS167",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS167",
		answer: "Có - Trước khai mạc 10-20 ngày",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS167",
		answer: "Có - Trước khai mạc 21 ngày",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS166",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS166",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS165",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS165",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS164",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS164",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS163",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS163",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS162",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS162",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS161",
		answer: "Có",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS161",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS161",
		answer: "Không áp dụng do pháp luật Việt Nam không yêu cầu",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS160",
		answer: "Có",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS160",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS160",
		answer: "Không áp dụng do pháp luật Việt Nam không yêu cầu",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS159",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS159",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS158",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS158",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS157",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS157",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS155",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS155",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS154",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS154",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS153",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS153",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS152",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS152",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS151",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS151",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS150",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS150",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS149",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS149",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS148",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS148",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS147",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS147",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS146",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS146",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS145",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS145",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS144",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS144",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS143",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS143",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS142",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS142",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS138",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS138",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS137",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS137",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS133",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS133",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS132",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS132",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS131",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS131",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS130",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS130",
		answer: "Có - Quy trình nội bộ",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS130",
		answer: "Có - Áp dụng công khai",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS129",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS129",
		answer: "Có - Áp dụng không đầy đủ",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS129",
		answer: "Có- Áp dụng đầy đủ",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS128",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS128",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS127",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS127",
		answer: "Có - Dưới 50% người lao động tham gia tập huấn",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS127",
		answer: "Có - Bằng hoặc trên 50% người lao động tham gia tập huấn",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS126",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS126",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS125",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS125",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS124",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS124",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS123",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS123",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS122",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS122",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS121",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS121",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS120",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS120",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS119",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS119",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS118",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS118",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS117",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS117",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS116",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS116",
		answer: "Có - Dưới 50% người lao động tham gia tập huấn",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS116",
		answer: "Có -Bằng hoặc trên 50% người lao động tham gia tập huấn",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS115",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS115",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS114",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS114",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS113",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS113",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS112",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS112",
		answer: "Có - Kiêm nhiệm",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS112",
		answer: "Có - Chuyên trách",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS111",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS111",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS110",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS110",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS109",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS109",
		answer: "Có - Theo pháp luật Việt Nam",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS109",
		answer: "Có - Theo pháp luật Việt Nam và cung cấp thêm các phúc lợi khác để thu hút nguồn lao động",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS105",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS105",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS104",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS104",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS102",
		answer: "Có - <3 Tháng 1 lần",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS102",
		answer: "Có - Từ 3 đến 5 tháng 1 lần",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS102",
		answer: "Có - Từ 6 tháng đến 1 năm 1 lần",
		dummy: "3",
		language: "vi",
	},
	{
		questionCode: "AS102",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS080",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS080",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS073",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS073",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS072",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS072",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS071",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS071",
		answer: "Có - Báo cáo không đầy đủ các thông tin",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS071",
		answer: "Có - Báo cáo đầy đủ các thông tin",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS071",
		answer: "Không áp dụng do không sử dụng nguyên vật liệu",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS070",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS070",
		answer: "Có - Báo cáo không đầy đủ các thông tin",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS070",
		answer: "Có - Báo cáo đầy đủ các thông tin",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS070",
		answer: "Không áp dụng do không phát thải chất thải",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS069",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS069",
		answer: "Có - Báo cáo không đầy đủ các thông tin",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS069",
		answer: "Có - Báo cáo đầy đủ các thông tin",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS069",
		answer: "Không áp dụng do không phát thải chất thải",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS068",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS068",
		answer: "Có - công bố nhưng không chi tiết theo loại nước thải và nguồn phát thải",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS068",
		answer: "Có - Công bố và báo cáo chi tiết theo loại nước thải và nguồn phát thải",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS068",
		answer: "Không áp dụng do không phát thải nước thải",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS066",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS066",
		answer: "Có - Theo pháp luật Việt Nam",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS066",
		answer: "Có - Theo pháp luật Việt Nam và chuẩn mực quốc tế",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS066",
		answer: "Không áp dụng do hoạt động của doanh nghiệp không ảnh hưởng đến đa dạng sinh học",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS065",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS065",
		answer: "Có - Thống kê lượng nước đầu vào, nhưng không sử dụng nước tuần hoàn và tái sử dụng",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS065",
		answer: "Có - Thống kê và đo lường lượng nước đầu vào, nước tuần hoàn và nước tái sử dụng",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS063",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS063",
		answer: "Có - Áp dụng không đầy đủ",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS063",
		answer: "Có - Áp dụng đầy đủ",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS062",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS062",
		answer: "Có - Dưới 50% người lao động tham gia tập huấn",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS062",
		answer: "Có - Bằng hoặc trên 50% người lao động tham gia tập huấn",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS061",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS061",
		answer: "Có - Kiêm nhiệm",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS061",
		answer: "Có - Chuyên trách",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS059",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS059",
		answer: "Có - Thực hiện báo cáo và công bố thông tin theo quy định pháp luật hoặc yêu cầu của các bên liên quan",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS059",
		answer: "Có - Tự nguyện thực hiện báo cáo và công bố thông tin",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS059",
		answer: "Không áp dụng do loại hình kinh doanh không yêu cầu",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS058",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS058",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS057",
		answer: "Có - Theo tiêu chuẩn Việt Nam và chuẩn mực quốc tế và công bố",
		dummy: "4",
		language: "vi",
	},
	{
		questionCode: "AS057",
		answer: "Có - Theo tiêu chuẩn Việt Nam và chuẩn mực quốc tế",
		dummy: "3",
		language: "vi",
	},
	{
		questionCode: "AS057",
		answer: "Có - Tự nguyện thực hiện/ Tuân thủ theo tiêu chuẩn Việt Nam và công bố",
		dummy: "2",
		language: "vi",
	},
	{
		questionCode: "AS057",
		answer: "Có - Tự nguyện thực hiện/ Tuân thủ theo tiêu chuẩn Việt Nam",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS057",
		answer: "Không",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS056",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS056",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS055",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS055",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS024",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS024",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS010",
		answer: "Yes",
		dummy: "1",
		language: "vi",
	},
	{
		questionCode: "AS010",
		answer: "No",
		dummy: "0",
		language: "vi",
	},
	{
		questionCode: "AS197",
		answer: "The Company does not accept third-party verification of scope 1 and 2 emissions or publicly disclose the results.",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS197",
		answer: "The company receives third-party verification for a portion of its Scope 1 and Scope 2 emissions and publicly discloses the results. The third-party verification is conducted at a limited assurance level.",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS197",
		answer: "The Company obtains full third-party verification for all scope 1 and 2 emissions and makes the results publicly available. Third-party verification is performed at a limited level of assurance.",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS197",
		answer: "The Company obtains third-party verification for all Scope 1 and 2 emissions and makes the results publicly available. Third-party verification is performed to a reasonable level of assurance, preferably by an Accredited Verifier.",
		dummy: "3",
		language: "en",
	},
	{
		questionCode: "AS196",
		answer: "The company do not monitor and publicly disclose energy usage",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS196",
		answer: "The company monitor and publicly disclose primary energy sources",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS196",
		answer: "The company tracks and publicly discloses all energy usage and has established an annual process to continue monitoring energy usage.",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS196",
		answer: "\nThe company has tracked and publicly disclosed all energy usage for at least 5 years and has established an annual process to continue monitoring energy usage.",
		dummy: "3",
		language: "en",
	},
	{
		questionCode: "AS195",
		answer: "The company does not calculate or publicly disclose any Scope 1 or Scope 2 emissions.",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS195",
		answer: "The company calculates and publicly discloses all major emissions sources of Scope 1 and Scope 2.",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS195",
		answer: "The Company calculates and publicly discloses all scope 1 and scope 2 emissions. The Company has established an annual process to continue disclosing scope 1 and 2 emissions.",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS195",
		answer: "\nThe company has calculated and publicly disclosed all Scope 1 and Scope 2 emissions for at least 5 years and has established an annual process to continue disclosing Scope 1 and Scope 2 emissions.",
		dummy: "3",
		language: "en",
	},
	{
		questionCode: "AS192",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS192",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS184",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS184",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS178",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS178",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS176",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS176",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS175",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS175",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS174",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS174",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS173",
		answer: "No ",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS173",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS173",
		answer: "Not applicable as Vietnamese law does not require it.",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS169",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS169",
		answer: "Yes- In VietNamese",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS169",
		answer: "Yes- In English",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS169",
		answer: "Yes - In both Vietnamese and English",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS168",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS168",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS167",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS167",
		answer: "Yes - 10-20 days before opening",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS167",
		answer: "Yes - 21 days before opening",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS166",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS166",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS165",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS165",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS164",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS164",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS163",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS163",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS162",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS162",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS161",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS161",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS161",
		answer: "Not applicable as Vietnamese law does not require it.",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS160",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS160",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS160",
		answer: "Not applicable as Vietnamese law does not require it.",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS159",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS159",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS158",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS158",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS157",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS157",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS155",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS155",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS154",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS154",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS153",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS153",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS152",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS152",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS151",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS151",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS150",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS150",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS149",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS149",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS148",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS148",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS147",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS147",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS146",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS146",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS145",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS145",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS144",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS144",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS143",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS143",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS142",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS142",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS138",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS138",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS137",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS137",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS133",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS133",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS132",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS132",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS131",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS131",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS130",
		answer: "Không",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS130",
		answer: "Yes - Internal Process",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS130",
		answer: "Yes - Publicly available",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS129",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS129",
		answer: "Yes - Not fully applicable",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS129",
		answer: "Yes - Fully applicable",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS128",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS128",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS127",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS127",
		answer: "Yes - Less than 50% of employees attend training",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS127",
		answer: "Yes - Equal to or more than 50% of employees participate in training",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS126",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS126",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS125",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS125",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS124",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS124",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS123",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS123",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS122",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS122",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS121",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS121",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS120",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS120",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS119",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS119",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS118",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS118",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS117",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS117",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS116",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS116",
		answer: "Yes - Less than 50% of employees attend training",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS116",
		answer: "Yes - Equal to or more than 50% of employees participate in training",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS115",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS115",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS114",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS114",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS113",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS113",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS112",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS112",
		answer: "Yes - Concurrent",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS112",
		answer: "Yes - Full-time",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS111",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS111",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS110",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS110",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS109",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS109",
		answer: "Yes - According to Vietnamese law",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS109",
		answer: "Yes - According to Vietnamese law and provide additional benefits to attract labor",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS105",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS105",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS104",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS104",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS102",
		answer: "Yes - <3 Months 1 Time",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS102",
		answer: "Yes - Every 3 to 5 months",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS102",
		answer: "Yes - Every 6 months to 1 year",
		dummy: "3",
		language: "en",
	},
	{
		questionCode: "AS102",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS080",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS080",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS073",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS073",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS072",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS072",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS071",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS071",
		answer: "Yes - Incomplete report of information",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS071",
		answer: "Yes - Report full information",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS071",
		answer: "Not applicable due to no raw materials used",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS070",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS070",
		answer: "Yes- Imcomplete report of information",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS070",
		answer: "Yes- Report full information ",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS070",
		answer: "Not applicable due to no waste emissions",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS069",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS069",
		answer: "Yes- Impcomplete report of information ",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS069",
		answer: "Yes- Report full information ",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS069",
		answer: "Not applicable due to no waste emissions",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS068",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS068",
		answer: "Yes - published but not detailed by wastewater type and emission source",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS068",
		answer: "Yes - Disclosure and detailed reporting by wastewater type and emission source",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS068",
		answer: "Not applicable due to no wastewater emissions",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS066",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS066",
		answer: "Yes - According to Vietnamese law",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS066",
		answer: "Yes - According to Vietnamese law and international standards",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS066",
		answer: "Not applicable because the business's activities do not affect biodiversity.",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS065",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS065",
		answer: "Yes - Statistics on the amount of incoming water, but does not use recycled and reused water.",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS065",
		answer: "Yes - Statistics and measurement of incoming water, recycled water, and reused water.",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS063",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS063",
		answer: "Yes- Impcomplete report of information ",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS063",
		answer: "Yes- Report full information ",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS062",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS062",
		answer: "Yes - Less than 50% of employees attend training",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS062",
		answer: "Yes- Qual to and more 50% of employees attend training ",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS061",
		answer: "No ",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS061",
		answer: "Yes - Concurrent",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS061",
		answer: "Yes- Full-time",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS059",
		answer: "No ",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS059",
		answer: "Yes - Report and disclose information as required by law or as required by relevant parties.",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS059",
		answer: "Yes - Voluntary reporting and disclosure",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS059",
		answer: "Not applicable due to business type not requiredNot applicable due to business type not required",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS058",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS058",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS057",
		answer: "Yes - According to Vietnamese standards and international standards and announcements",
		dummy: "4",
		language: "en",
	},
	{
		questionCode: "AS057",
		answer: "Yes - According to Vietnamese and international standards",
		dummy: "3",
		language: "en",
	},
	{
		questionCode: "AS057",
		answer: "Yes - Voluntarily implement/Comply with Vietnamese standards and publish",
		dummy: "2",
		language: "en",
	},
	{
		questionCode: "AS057",
		answer: "Yes - Voluntary implementation/Compliance with Vietnamese standards",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS057",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS056",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS056",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS055",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS055",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS024",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS024",
		answer: "No",
		dummy: "0",
		language: "en",
	},
	{
		questionCode: "AS010",
		answer: "Yes",
		dummy: "1",
		language: "en",
	},
	{
		questionCode: "AS010",
		answer: "No",
		dummy: "0",
		language: "en",
	},
];
