module.exports = [
	{
		questionCode: "AS197",
		topicCode: "E51",
		name: "Doanh nghiệp của bạn có nhận xác minh từ bên thứ ba cho phạm vi 1 và 2 khí thải và công bố công khai kết quả không?",
		answer1:
			"Doanh nghiệp không nhận xác minh từ bên thứ ba cho lượng khí thải phạm vi 1 và 2 hoặc công bố công khai kết quả.",
		answer2:
			"Doanh nghiệp nhận xác minh từ bên thứ ba cho một phần lượng khí thải phạm vi 1 và 2 và công bố kết quả công khai. Việc xác minh bên thứ ba được thực hiện ở mức độ đảm bảo hạn chế.",
		answer3:
			"Doanh nghiệp nhận xác minh đầy đủ từ bên thứ ba cho tất cả lượng khí thải phạm vi 1 và 2 và công bố công khai kết quả. Việc xác minh bên thứ ba được thực hiện ở mức độ đảm bảo hạn chế.",
		answer4:
			"Doanh nghiệp nhận xác minh từ bên thứ ba cho tất cả lượng khí thải phạm vi 1 và 2 và công bố công khai kết quả. Việc xác minh từ bên thứ ba được thực hiện ở mức độ đảm bảo hợp lý, tốt nhất là từ một Doanh nghiệp xác minh được công nhận.",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS196",
		topicCode: "E50",
		name: "Doanh nghiệp của bạn có theo dõi và công bố công khai mức sử dụng năng lượng không?",
		answer1:
			"Doanh nghiệp không theo dõi và công bố công khai mức sử dụng năng lượng",
		answer2:
			"Doanh nghiệp theo dõi và công cố công khai các nguồn năng lượng chính",
		answer3:
			"Doanh nghiệp theo dõi và công bố công khai tất cả mức sử dụng năng lượng và đã tạo ra quy trình hàng năm để tiếp tục theo dõi mức sử dụng năng lượng",
		answer4:
			"Doanh nghiệp đã theo dõi và công bố công khai tất cả mức sử dụng năng lượng trong ít nhất 5 năm và đã tạo ra quy trình hàng năm để tiếp tục theo dõi mức sử dụng năng lượng",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS195",
		topicCode: "E49",
		name: "Doanh nghiệp của bạn có tính toán và công bố công khai lượng khí thải phạm vi 1 và phạm vi 2 không?",
		answer1:
			"Doanh nghiệp không tính toán và công bố công khai bất kỳ lượng khí thải phạm vi 1 hoặc phạm vi 2 nào",
		answer2:
			"Doanh nghiệp tính toán và công bố công khai tất cả các nguồn phát thải chính của phạm vi 1 và phạm vi 2",
		answer3:
			"Doanh nghiệp tính toán và công bố công khai tất cả lượng phát thải phạm vi 1 và phạm vi 2. Doanh nghiệp đã tạo quy trình hàng năm để tiếp tục công bố lượn khí thải phạm vi 1 và 2",
		answer4:
			"Doanh nghiệp đã tính toán và công bố công khai tất cả lượng khí thải phạm vi 1 và phạm vi 2 trong ít nhất 5 năm và đã tạo ra quy trình hàng năm và tiếp tục công bố lượng khí thải phạm vi 1 và 2",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS193",
		topicCode: "S71",
		name: "Số nhân viên là người nước ngoài của doanh nghiệp",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS194",
		topicCode: " ",
		name: "Giá nước trung bình năm trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS192",
		topicCode: "G53",
		name: "Doanh nghiệp có đạt được chứng nhận ISO 37001 về hệ thống quản lý chống hối lộ chưa?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS191",
		topicCode: "G52",
		name: "Có bao nhiêu nhà cung cấp được doanh nghiệp đánh giá lại hàng năm",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS190",
		topicCode: "G51",
		name: "Số thành viên giới tính nam trong HĐQT",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS189",
		topicCode: "G50",
		name: "Số thành viên giới tính nữ trong HĐQT",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS187",
		topicCode: "G44",
		name: "Số trường hợp vi phạm hình sự của doanh nghiệp",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS186",
		topicCode: "G44",
		name: "Số trường hợp vi phạm hành chính của doanh nghiệp",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS185",
		topicCode: "G44",
		name: "Số trường hợp vi phạm kỷ luật của doanh nghiệp",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS184",
		topicCode: "G43",
		name: "Doanh nghiệp có thống kê về các trường hợp vi phạm của lao động trong  doanh nghiệp hàng năm không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS183",
		topicCode: "G42",
		name: "Số vụ việc vi phạm quy định về hạn chế cạnh tranh",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS182",
		topicCode: "G41",
		name: "Số vụ việc vi phạm quy định về quảng cáo (Luật quảng cáo 2012)",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS181",
		topicCode: "G40",
		name: "Số vụ việc vi phạm quy định về tham ô tài sản; đưa, nhận và môi giới hối lộ qua từng năm",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS180",
		topicCode: "G39",
		name: "Số lượng nhà cung ứng quan trọng của doanh nghiệp",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS179",
		topicCode: "G38",
		name: "Số lượng nhà cung ứng cấp 1 của doanh nghiệp",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS178",
		topicCode: "G36",
		name: "Doanh nghiệp có đánh giá các nhà cung ứng qua các năm không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS177",
		topicCode: "G35",
		name: "Doanh nghiệp có tất cả bao nhiêu nhà cung ứng",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS176",
		topicCode: "G34",
		name: "Doanh nghiệp có thực hiện chi trả cổ tức đầy đủ trong thời hạn 06 tháng, kể từ ngày kết thúc họp Đại hội đồng cổ đông thường niên?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS175",
		topicCode: "G33",
		name: "Trong năm gần nhất, đại hội đồng cổ đông có thông qua thù lao hoặc lương thưởng, chi phí, các khoản lợi ích do doanh nghiệp thanh toán cho từng thành viên Hội đồng Quản trị không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS174",
		topicCode: "G32",
		name: "Doanh nghiệp có xây dựng và công bố chính sách liên quan đến việc khiếu nại của cổ đông không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS173",
		topicCode: "G31",
		name: "Trong trường hợp doanh nghiệp bắt buộc phải có Kiểm toán độc lập theo pháp luật Việt Nam, doanh nghiệp có công bố đã bổ nhiệm một bên độc lập (kiểm tra, giám sát viên) là Kiểm toán độc lập không?",
		answer1: "Không",
		answer2: "Có",
		answer3: "Không áp dụng do pháp luật Việt Nam không yêu cầu",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS169",
		topicCode: "G30",
		name: "Trong năm gần nhất, doanh nghiệp có công bố và sử dụng tài liệu họp, biên bản họp, nghị quyết Đại Hội Đồng Cổ Đông bằng tiếng Việt và tiếng Anh?",
		answer1: "Không",
		answer2: "Có  - Bằng tiếng Việt",
		answer3: "Có - Bằng tiếng Anh",
		answer4: "Có - Bằng cả tiếng Việt và tiếng Anh",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS168",
		topicCode: "G29",
		name: "Trong thư mời tham dự Đại Hội Đồng Cổ Đông, cổ đông có được hướng dẫn để đóng góp ý kiến trong thời gian trước ngày tham dự đại hội về (các) vấn đề thảo luận trong chương trình nghị sự của Đại Hội Đồng Cổ Đông không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS167",
		topicCode: "G28",
		name: "Trong năm gần nhất, tài liệu họp Đại Hội Đồng Cổ Đông có cung cấp thông tin về các ứng viên Hội đồng quản trị và Ban Kiểm Soát (nếu có) tối thiểu 10 ngày\ntrước ngày khai mạc đại hội không",
		answer1: "Không",
		answer2: "Có - Trước khai mạc 10-20 ngày",
		answer3: "Có - Trước khai mạc 21 ngày",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS166",
		topicCode: "G26",
		name: "Trong năm gần nhất, doanh nghiệp có công bố tính độc lập của thành viên HĐQT không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS165",
		topicCode: "G25",
		name: "Doanh nghiệp có bộ phận chịu trách nhiệm giám sát truyền thông ra bên ngoài và lưu trữ thông tin theo quy định của pháp luật không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS164",
		topicCode: "G24",
		name: "Chủ tịch Ủy ban Quản lý rủi ro có phải là thành viên độc lập HĐQT không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS163",
		topicCode: "G23",
		name: "Doanh nghiệp có thành lập Ủy ban Quản lý rủi ro không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS162",
		topicCode: "G22",
		name: "Trong năm qua, chủ tịch Ủy ban kiểm toán có phải là Thành viên độc lập HĐQT không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS161",
		topicCode: "G21",
		name: "Trong trường hợp doanh nghiệp bắt buộc phải có Ban Kiểm soát theo pháp luật Việt Nam, doanh nghiệp có thành lập Ban Kiểm soát không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "Không áp dụng do pháp luật Việt Nam không yêu cầu",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS160",
		topicCode: "G20",
		name: "Trong trường hợp doanh nghiệp bắt buộc phải có Kiểm toán nội bộ theo pháp luật Việt Nam, danh sách các ứng viên kiểm toán có được công bố công khai không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "Không áp dụng do pháp luật Việt Nam không yêu cầu",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS159",
		topicCode: "G19",
		name: "Doanh nghiệp có thành lập bộ phận Kiểm toán nội bộ không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS158",
		topicCode: "G18",
		name: "Trong năm gần nhất, báo cáo đánh giá về hoạt động của HĐQT có phải do thành viên độc lập đánh giá không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS157",
		topicCode: "G17",
		name: "Doanh nghiệp có đảm bảo tối thiểu 20% tổng số thành viên của HĐQT là thành viên độc lập không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS156",
		topicCode: "G16",
		name: "Trong năm gần nhất, tỷ lệ tiểu ban trực thuộc Hội đồng quản trị do Thành viên độc lập làm trưởng ban là bao nhiêu?",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS155",
		topicCode: "G15",
		name: "Doanh nghiệp niêm yết có thành lập các tiểu ban sau: tiểu ban chính sách phát triển, tiểu ban nhân sự, tiểu ban lương thưởng hay các đơn vị tương đương không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS154",
		topicCode: "G14",
		name: "Báo cáo thường niên có công bố phát biểu, tuyên bố khẳng định sự tuân thủ đầy đủ của doanh nghiệp với các quy tắc quản trị doanh nghiệp và trong trường hợp có việc không tuân thủ, báo cáo có nếu rõ và giải thích lý do cho mỗi vấn đề đó không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS153",
		topicCode: "G13",
		name: "Báo cáo thường niên có công bố mức lương, thưởng, các khoản thu nhập khác, quỹ phúc lợi và chi phí mà doanh nghiệp chi trả, thanh toán cho từng thành viên trong HĐQT hoặc HĐTV hoặc Ban Giám đốc không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS152",
		topicCode: "G12",
		name: "Trong năm gần nhất, tiền lương của người điều hành hoạt động kinh doanh (Giám đốc, Tổng giám đốc, v.v) có được thể hiện thành mục riêng trong Báo cáo tài chính hàng năm của doanh nghiệp và được công khai hoặc báo cáo Đại hội đồng cổ đông, hoặc Ban giám đốc tại cuộc họp thường niên không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS151",
		topicCode: "G11",
		name: "Trong năm gần nhất, doanh nghiệp có thường xuyên cập nhật các nội dung trên website doanh nghiệp và bảo đảm mọi thông tin được cập nhật đều bằng cả tiếng Việt và tiếng Anh không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS150",
		topicCode: "G10",
		name: "Trong năm gần nhất, doanh nghiệp có xây dựng và công bố Báo cáo đánh giá liên quan đến trách nhiệm về môi trường, xã hội và tình hình tài chính không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS149",
		topicCode: "G9",
		name: "Doanh nghiệp có cơ chế tiếp nhận tố giác, khiếu nại, góp ý và giải quyết tố giác, khiếu nại, ý kiến từ các bên liên quan về các hoạt động của doanh nghiệp không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS148",
		topicCode: "G8",
		name: "Doanh nghiệp có cá nhân, thành viên của ban điều hành chịu trách nhiệm tiếp nhận ý kiến từ các bên liên quan không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS147",
		topicCode: "G7",
		name: "Doanh nghiệp có ban hành và công bố Bộ quy tắc ứng xử/ Đạo đức riêng hoặc có các nội dung về quy tắc ứng xử/ Đạo đức trong nội quy công ty không? (Điều 118 Bộ Luật Lao động 2019)",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS146",
		topicCode: "G6",
		name: "Doanh nghiệp có thiết lập quy trình để theo dõi việc thực hiện các khuyến nghị mà kiểm toán độc lập đưa ra không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS145",
		topicCode: "G5",
		name: "Doanh nghiệp có chính sách giới hạn về số năm đương nhiệm của thành viên HĐQT hoặc HĐTV hoặc Ban Giám đốc không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS144",
		topicCode: "G4",
		name: "Trong năm gần nhất, HĐQT hoặc HĐTV hoặc Ban Giám đốc có ban hành quy trình theo dõi, đánh giá công tác quản trị doanh nghiệp và việc tuân thủ pháp luật về quản trị doanh nghiệp không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS143",
		topicCode: "G2",
		name: "Cơ cấu HĐQT hoặc HĐTV hoặc ban Giám đốc có đa dạng về kiến thức và kinh nghiệm về pháp luật, tài chính, lĩnh vực hoạt động kinh doanh của doanh nghiệp\nkhông?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS142",
		topicCode: "G1",
		name: "Doanh nghiệp có chính sách phát triển bền vững rõ ràng và cam kết thực hiện các chính sách và hoạt động hướng đến phát triển bền vững không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS141",
		topicCode: "S68",
		name: "Số nhân viên là người khuyết tật của doanh nghiệp",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS140",
		topicCode: "S67",
		name: "Tổng số giờ đào tạo nhân viên trong năm gần nhất",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS139",
		topicCode: "S66",
		name: "Mức chi tiêu của doanh nghiệp cho các hệ thống bảo mật thông tin khách hàng",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS138",
		topicCode: "S65",
		name: "Doanh nghiệp có biện pháp kiểm soát việc sử dụng lao động cưỡng bức đối với các bên liên quan trong chuỗi cung ứng không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS137",
		topicCode: "S64",
		name: "Doanh nghiệp có trao đổi với các bên liên quan trong chuỗi cung ứng về vấn đề kiểm soát sử dụng lao động trẻ em thường xuyên không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS136",
		topicCode: "S52",
		name: "Mức chi phí doanh nghiệp bỏ ra để đào tạo và phát triển nhân viên",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS135",
		topicCode: "S51",
		name: "Số nhân viên được đào tạo trong năm gần nhất",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS134",
		topicCode: "S50",
		name: "Số khoá đào tạo nhân viên của doanh nghiệp trong năm gần nhất",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS133",
		topicCode: "S48",
		name: "Trong năm gần nhất, doanh nghiệp có bị khiếu nại liên quan đến vi phạm bảo mật thông tin khách hàng không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS132",
		topicCode: "S47",
		name: "Doanh nghiệp có thông báo đầy đủ và đúng thông tin sản phẩm, dịch vụ đến khách hàng hay không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS131",
		topicCode: "S46",
		name: "Trong năm gần nhất, doanh nghiệp có các vụ việc vi phạm các quy định về an toàn của sản phẩm với sức khỏe của người sử dụng không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS130",
		topicCode: "S45",
		name: "Doanh nghiệp có quy trình đánh giá nhằm đảm bảo sản phẩm, dịch vụ an toàn cho khách hàng không?",
		answer1: "Không",
		answer2: "Có - Quy trình nội bộ",
		answer3: "Có - Áp dụng công khai",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS129",
		topicCode: "S44",
		name: "Doanh nghiệp có tiêu chí/ tiêu chuẩn xã hội cho nhà cung cấp không?",
		answer1: "Không",
		answer2: "Có - Áp dụng không đầy đủ",
		answer3: "Có- Áp dụng đầy đủ",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS128",
		topicCode: "S43",
		name: "Trong năm gần nhất, doanh nghiệp có tổ chức các hoạt động gắn kết với cộng đồng địa phương, có sự tham gia của cộng đồng địa phương hay tác động tích cực đến cộng đồng địa phương không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS127",
		topicCode: "S42",
		name: "Trong năm gần nhất, doanh nghiệp có tiến hành đào tạo cho nhân viên hiểu về quyền lợi của mình khi làm việc tại doanh nghiệp cũng như các quyền lợi cơ bản khác theo quy định pháp luật không?",
		answer1: "Không",
		answer2: "Có - Dưới 50% người lao động tham gia tập huấn",
		answer3: "Có - Bằng hoặc trên 50% người lao động tham gia tập huấn",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS126",
		topicCode: "S41",
		name: "Trong năm gần nhất, doanh nghiệp có sử dụng lao động cưỡng bức không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS125",
		topicCode: "S40",
		name: "Trong năm gần nhất, doanh nghiệp có lao động từ đủ 15 đến dưới 18 tuổi trái quy định pháp luật không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS124",
		topicCode: "S39",
		name: "Trong năm gần nhất, doanh nghiệp có sử dụng lao động từ đủ 13 đến dưới 15 tuổi ngoài danh mục cho phép không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS123",
		topicCode: "S38",
		name: "Doanh nghiệp có thúc đẩy người lao động tham gia công đoàn, các tổ chức đoàn thể khác và thúc đẩy các hoạt động thương lượng tập thể nhưng không vi phạm pháp luật và chính sách doanh nghiệp không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS122",
		topicCode: "S37",
		name: "Doanh nghiệp có chính sách và sáng kiến tạo điều kiện khuyến khích sự tham gia của nhóm yếu thế vào chuỗi giá trị của doanh nghiệp hay không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS121",
		topicCode: "S36",
		name: "Doanh nghiệp có cơ chế tố giác và bảo vệ danh tính và sự an toàn của người tố cáo về các vấn đề phân biệt đối xử, bất bình đẳng, quấy rối tình dục không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS120",
		topicCode: "S35",
		name: "Trong năm gần nhất, những vụ việc phân biệt đối xử được báo cáo có được phân loại không",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS119",
		topicCode: "S34",
		name: "Trong năm gần nhất, doanh nghiệp có lập báo cáo vụ việc phân biệt đối xử xảy ra trong khoảng thời gian này không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS118",
		topicCode: "S32",
		name: "Trong năm gần nhất, doanh nghiệp có tổng hợp, lưu trữ thông tin/dữ liệu sự đa dạng của lực lượng lao động trong ban quản lý không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS117",
		topicCode: "S31",
		name: "Trong năm gần nhất, doanh nghiệp có tổng hợp, lưu trữ thông tin/ dữ liệu về sự đa dạng của toàn bộ người lao động trong doanh nghiệp không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS116",
		topicCode: "S30",
		name: "Trong năm gần nhất, doanh nghiệp có tiến hành tập huấn cho nhân viên về các chính sách an toàn và sức khoẻ của doanh nghiệp không?",
		answer1: "Không",
		answer2: "Có - Dưới 50% người lao động tham gia tập huấn",
		answer3: "Có -Bằng hoặc trên 50% người lao động tham gia tập huấn",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS115",
		topicCode: "S29",
		name: "Trong năm gần nhất, doanh nghiệp có trao đổi chính thức với Công đoàn hoặc các bên liên quan về các vấn đề sức khỏe và an toàn cho người lao động không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS114",
		topicCode: "S28",
		name: "Trong năm gần nhất, doanh nghiệp có tổng hợp, lưu trữ và công bố thông tin/ dữ liệu về tỷ lệ người lao động có nguy cơ cao mắc các bệnh nghề nghiệp không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS113",
		topicCode: "S69",
		name: "Doanh nghiệp có tuân thủ tiêu chuẩn OHSAS 18001 hoặc UNI EN ISO 45001 về sức khoẻ và an toàn nghề nghiệp của nhân viên không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS112",
		topicCode: "S26",
		name: "Doanh nghiệp có nhân sự phụ trách về các vấn đề an toàn và sức khoẻ nghề nghiệp không?",
		answer1: "Không",
		answer2: "Có - Kiêm nhiệm",
		answer3: "Có - Chuyên trách",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS111",
		topicCode: "S24",
		name: "Trong năm gần nhất, doanh nghiệp có tuân thủ thời gian làm việc theo luật lao động bao gồm cả trả lương làm thêm giờ, làm ca đêm và làm việc vào ngày lễ, ngày nghỉ chính thức cho người lao động không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS110",
		topicCode: "S23",
		name: "Doanh nghiệp có tổng hợp, lưu trữ thông tin/ dữ liệu về người lao động toàn thời gian nghỉ thai sản, quay trở lại làm việc và giữ được việc sau 12 tháng không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS109",
		topicCode: "S22",
		name: "Trong năm gần nhất, doanh nghiệp có thực hiện đầy đủ các chế độ phúc lợi cho người lao động theo quy định của pháp luật về lao động không?",
		answer1: "Không",
		answer2: "Có - Theo pháp luật Việt Nam",
		answer3:
			"Có - Theo pháp luật Việt Nam và cung cấp thêm các phúc lợi khác để thu hút nguồn lao động",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS108",
		topicCode: "S21",
		name: "Số lượng nhân viên được thuê mới",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS107",
		topicCode: "S21",
		name: "Số lượng nhân viên nghỉ việc không tự nguyện",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS106",
		topicCode: "S21",
		name: "Số lượng nhân viên nghỉ việc tự nguyện",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS105",
		topicCode: "S20",
		name: "Doanh nghiệp có xây dựng quy chế trả lương cho người lao động và chi trả ở mức bằng hoặc cao hơn lương tối thiểu vùng theo quy định của pháp luật không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS104",
		topicCode: "S19",
		name: "Doanh nghiệp có ký kết đầy đủ các loại hợp đồng với tất cả người lao động theo quy định của pháp luật không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS103",
		topicCode: "S18",
		name: "Điểm hài lòng của nhân viên về công ty là bao nhiêu",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS102",
		topicCode: "S17",
		name: "Doanh nghiệp có thường xuyên khảo sát mức độ hài lòng của nhân viên về công ty không?",
		answer1: "Có - <3 Tháng 1 lần",
		answer2: "Có - Từ 3 đến 5 tháng 1 lần",
		answer3: "Có - Từ 6 tháng đến 1 năm 1 lần",
		answer4: "Không",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS101",
		topicCode: "S16",
		name: "Số lượng người mắc bệnh nghề nghiệp trong năm gần nhất",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS100",
		topicCode: "S15",
		name: "Số lượng người bị tử vong do tai nạn lao động trong năm gần nhất",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS099",
		topicCode: "S14",
		name: "Số vụ tai nạn lao động của doanh nghiệp trong năm gần nhất",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS098",
		topicCode: "S13",
		name: "Mức thu nhập trung bình của nhân viên nữ ở cấp nhân viên trong năm trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS097",
		topicCode: "S12",
		name: "Mức thu nhập trung bình của nhân viên nam ở cấp nhân viên trong năm trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS096",
		topicCode: "S11",
		name: "Mức thu nhập trung bình của nhân viên nữ ở cấp trưởng dự án, trưởng phòng,… trong năm trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS095",
		topicCode: "S10",
		name: "Mức thu nhập trung bình của nhân viên nam ở cấp trưởng dự án, trưởng phòng,… trong năm trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS094",
		topicCode: "S9",
		name: "Mức thu nhập trung bình của nhân viên nữ ở cấp C-level trong năm trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS093",
		topicCode: "S8",
		name: "Mức thu nhập trung bình của nhân viên nam ở cấp C-level trong năm trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS092",
		topicCode: "S63",
		name: "Số nhân viên nghỉ việc mỗi trong năm trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS091",
		topicCode: "S62",
		name: "Số nhân viên được tuyển mới trong năm trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS090",
		topicCode: "S61",
		name: "Số lượng nhân viên nữ ở cấp bậc nhân viên",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS089",
		topicCode: "S60",
		name: "Số lượng nhân viên nam ở cấp bậc nhân viên",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS088",
		topicCode: "S59",
		name: "Số lượng nhân viên nữ ở cấp bậc trưởng dự án, trưởng phòng",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS087",
		topicCode: "S58",
		name: "Số lượng nhân viên nam ở cấp bậc trưởng dự án, trưởng phòng,…",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS086",
		topicCode: "S57",
		name: "Số lượng nhân viên nữ ở cấp bậc C-level",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS085",
		topicCode: "S56",
		name: "Số lượng nhân viên nam ở cấp bậc C-level",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS084",
		topicCode: "S55",
		name: "Số lượng nhân viên nữ của doanh nghiệp",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS083",
		topicCode: "S54",
		name: "Số lượng nhân viên nam của doanh nghiệp",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS082",
		topicCode: "S53",
		name: "Tổng số lượng nhân viên của doanh nghiệp",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS081",
		topicCode: "S7",
		name: "Có bao nhiêu nhân viên của công ty tham gia các tổ chức đại diện người lao động tại cơ sở?",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS080",
		topicCode: "S6",
		name: "Doanh nghiệp có tổ chức đại diện người lao động tại cơ sở (Công đoàn) không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS076",
		topicCode: "S4",
		name: "Tổng mức chi tiêu của doanh nghiệp cho các hoạt động xã hội",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS075",
		topicCode: "S3",
		name: "Số hoạt động xã hội trung bình mà 1 nhân viên tham gia/ năm",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS073",
		topicCode: "S1",
		name: "Doanh nghiệp có quyên góp, tổ chức, tham gia các hoạt động xã hội hàng năm không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS072",
		topicCode: "S70",
		name: "Doanh nghiệp có tuân thủ tiêu chuẩn ISO 26000 về trách nhiệm xã hội không",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS071",
		topicCode: "E46",
		name: "Trong năm trước, doanh nghiệp có theo dõi và báo cáo về tỷ trọng các loại nguyên vật liệu có thể tái chế trong cơ cấu sản phẩm không? (bao gồm cả nguyên liệu đóng gói trong quá trình phân phối)",
		answer1: "Không",
		answer2: "Có - Báo cáo không đầy đủ các thông tin",
		answer3: "Có - Báo cáo đầy đủ các thông tin",
		answer4: "Không áp dụng do không sử dụng nguyên vật liệu",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS070",
		topicCode: "E45",
		name: "Trong năm gần nhất, doanh nghiệp có tổng hợp, lưu trữ và công bố thông tin/ dữ liệu việc vận chuyển chất thải nguy hại không?",
		answer1: "Không",
		answer2: "Có - Báo cáo không đầy đủ các thông tin",
		answer3: "Có - Báo cáo đầy đủ các thông tin",
		answer4: "Không áp dụng do không phát thải chất thải",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS069",
		topicCode: "E44",
		name: "Trong năm gần nhất, doanh nghiệp có tổng hợp, lưu trữ và công bố thông tin/ dữ liệu về tổng lượng chất thải, bao gồm chất thải nguy hại, chất thải không nguy hại, và phương pháp xử lý chất thải không?",
		answer1: "Không",
		answer2: "Có - Báo cáo không đầy đủ các thông tin",
		answer3: "Có - Báo cáo đầy đủ các thông tin",
		answer4: "Không áp dụng do không phát thải chất thải",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS068",
		topicCode: "E43",
		name: "Trong năm gần nhất, doanh nghiệp có tổng hợp, lưu trữ và công bố thông tin/ dữ liệu về tổng lượng nước thải theo chất lượng không?",
		answer1: "Không",
		answer2:
			"Có - công bố nhưng không chi tiết theo loại nước thải và nguồn phát thải",
		answer3:
			"Có - Công bố và báo cáo chi tiết theo loại nước thải và nguồn phát thải",
		answer4: "Không áp dụng do không phát thải nước thải",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS066",
		topicCode: "E41",
		name: "Trong năm gần nhất, doanh nghiệp có đánh giá và giám sát các hoạt động của doanh nghiệp mà có tác động đáng kể đến đa dạng sinh học không?",
		answer1: "Không",
		answer2: "Có - Theo pháp luật Việt Nam",
		answer3: "Có - Theo pháp luật Việt Nam và chuẩn mực quốc tế",
		answer4:
			"Không áp dụng do hoạt động của doanh nghiệp không ảnh hưởng đến đa dạng sinh học",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS065",
		topicCode: "E40",
		name: "Trong năm gần nhất, doanh nghiệp có theo dõi và thống kê lượng nước đầu vào (nước mặt, nước sâu), nước tuần hoàn và tái sử dụng không?",
		answer1: "Không",
		answer2:
			"Có - Thống kê lượng nước đầu vào, nhưng không sử dụng nước tuần hoàn và tái sử dụng",
		answer3:
			"Có - Thống kê và đo lường lượng nước đầu vào, nước tuần hoàn và nước tái sử dụng",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS063",
		topicCode: "E37",
		name: "Doanh nghiệp có tiêu chí/ tiêu chuẩn môi trường cho nhà cung ứng không?",
		answer1: "Không",
		answer2: "Có - Áp dụng không đầy đủ",
		answer3: "Có - Áp dụng đầy đủ",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS062",
		topicCode: "E36",
		name: "Trong năm gần nhất, doanh nghiệp có tập huấn nội bộ chính sách môi trường của doanh nghiệp không?",
		answer1: "Không",
		answer2: "Có - Dưới 50% người lao động tham gia tập huấn",
		answer3: "Có - Bằng hoặc trên 50% người lao động tham gia tập huấn",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS061",
		topicCode: "E35",
		name: "Doanh nghiệp có nhân sự phụ trách về vấn đề môi trường không?",
		answer1: "Không",
		answer2: "Có - Kiêm nhiệm",
		answer3: "Có - Chuyên trách",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS059",
		topicCode: "E33",
		name: "Trong năm gần nhất, doanh nghiệp có thực hiện báo cáo, công bố thông tin về công tác quản lý môi trường không?",
		answer1: "Không",
		answer2:
			"Có - Thực hiện báo cáo và công bố thông tin theo quy định pháp luật hoặc yêu cầu của các bên liên quan",
		answer3: "Có - Tự nguyện thực hiện báo cáo và công bố thông tin",
		answer4: "Không áp dụng do loại hình kinh doanh không yêu cầu",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS058",
		topicCode: "E32",
		name: "Trong năm gầnn nhất, doanh nghiệp có bị xử phạt vi phạm liên quan tới môi trường không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS057",
		topicCode: "E31",
		name: "Doanh nghiệp có chính sách quản lý, giám sát và đánh giá tác động môi trường và công bố chính sách rộng rãi (ví dụ trên website của doanh nghiệp) này không?",
		answer1:
			"Có - Theo tiêu chuẩn Việt Nam và chuẩn mực quốc tế và công bố",
		answer2: "Có - Theo tiêu chuẩn Việt Nam và chuẩn mực quốc tế",
		answer3:
			"Có - Tự nguyện thực hiện/ Tuân thủ theo tiêu chuẩn Việt Nam và công bố",
		answer4: "Có - Tự nguyện thực hiện/ Tuân thủ theo tiêu chuẩn Việt Nam",
		answer5: "Không",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "2",
	},
	{
		questionCode: "AS056",
		topicCode: "E26",
		name: "Doanh nghiệp có triển khai hoạt động nghiên cứu và phát triển sản phẩm theo hướng phát triển bền vững không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS055",
		topicCode: "E25",
		name: "Doanh nghiệp có hệ thống quản lý tác động môi trường không",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS028",
		topicCode: "E19",
		name: "Lượng mực in doanh nghiệp sử dụng trong năm trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS027",
		topicCode: "E18",
		name: "Lượng nước doanh nghiệp tái chế trong năm trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS026",
		topicCode: "E17",
		name: "Mức chi tiêu của doanh nghiệp cho các vấn đề môi trường trong năm trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS025",
		topicCode: "E16",
		name: "Lượng giấy doanh nghiệp sử dụng trong năm trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS024",
		topicCode: "E15",
		name: "Doanh nghiệp có áp dụng chuyển đối số, IoT trong tiết kiệm năng lượng không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS023",
		topicCode: "E14",
		name: "Lượng điện tiêu thụ của doanh nghiệp từ các nguồn khác",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS022",
		topicCode: "E14",
		name: "Lượng điện tiêu thụ của doanh nghiệp từ nguồn năng lượng tái tạo",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS021",
		topicCode: "E14",
		name: "Lượng điện tiêu thụ của doanh nghiệp từ nguồn điện lưới quốc gia",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS019",
		topicCode: "E13",
		name: "Tổng tiền nước của doanh nghiệp ở các chi nhánh năm trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS018",
		topicCode: "E12",
		name: "Tiền nước của doanh nghiệp ở trụ sở chính năm trước năm trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS017",
		topicCode: "E11",
		name: "Tổng tiền điện của doanh nghiệp ở các chi nhánh năm trước",
		answer1: "a",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS015",
		topicCode: "E47",
		name: "Khối lượng rác thải nguy hại phải xử lí đặc biệt",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS014",
		topicCode: "E10",
		name: "Tiền điện của doanh nghiệp ở trụ sở chính năm trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS013",
		topicCode: "E7",
		name: "Khối lượng rác thải có thể tái chế",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS012",
		topicCode: "E6",
		name: "Khối lượng rác thải hữu cơ",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS011",
		topicCode: "E5",
		name: "Khối lượng rác thải vô cơ",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS010",
		topicCode: "E4",
		name: "Doanh nghiệp có quy định về việc phân loại rác thải tại nguồn không?",
		answer1: "Có",
		answer2: "Không",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "1",
	},
	{
		questionCode: "AS009",
		topicCode: "E3",
		name: "Khối lượng bao bì có thể tái chế được doanh nghiệp sử dụng năm gần nhất",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS008",
		topicCode: "E2",
		name: "Khối lượng bao bì nhựa doanh nghiệp sử dụng năm gần nhất",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS006",
		topicCode: "A15",
		name: "Công ty có bao nhiêu chi nhánh?",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS005",
		topicCode: "A15",
		name: "Công ty có bao nhiêu cửa hàng?",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS004",
		topicCode: "A14",
		name: "Số nhân viên toàn thời gian",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS003",
		topicCode: "A13",
		name: "Số nhân viên bán thời gian",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS002",
		topicCode: "A12",
		name: "Lợi nhuận sau thuế của công ty trong năm tài chính trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
	{
		questionCode: "AS001",
		topicCode: "A11",
		name: "Doanh thu thuần của công ty trong năm tài chính trước",
		answer1: "0",
		answer2: "0",
		answer3: "0",
		answer4: "0",
		answer5: "0",
		answer6: "0",
		answer7: "0",
		answer8: "0",
		answer9: "0",
		answer10: "0",
		type: "3",
	},
];
