module.exports = [
	{ sectionName: "GENERAL_INFORMATION", sectionId: 1 },
	{ sectionName: "PACKAGING", sectionId: 2 },
	{ sectionName: "WASTE", sectionId: 3 },
	{ sectionName: "ELECTRICITY", sectionId: 4 },
	{ sectionName: "WATER", sectionId: 5 },
	{ sectionName: "PAPER_INK", sectionId: 6 },
	{ sectionName: "ENVIRONMENTAL_MANAGEMENT", sectionId: 7 },
	{
		sectionName: "ENVIRONMENT_COMPLIANCE_REPORTING_ASSESSMENT",
		sectionId: 8,
	},
	{
		sectionName: "ENVIRONMENTAL_DATA_COLLECTION_REPORTING_STANDARD_AUDIT",
		sectionId: 9,
	},
	{ sectionName: "GENERAL_SOCIAL", sectionId: 10 },
	{ sectionName: "EMPLOYEE_OVERVIEW", sectionId: 11 },
	{ sectionName: "EMPLOYEE_INFORMATION", sectionId: 12 },
	{ sectionName: "EMPLOYEE_RESIGNATION_NEW", sectionId: 13 },
	{ sectionName: "INCOME_BY_LEVEL", sectionId: 14 },
	{ sectionName: "RISK_AT_WORK", sectionId: 15 },
	{ sectionName: "RELATIONSHIP_EMPLOYEE_ENTERPRISES", sectionId: 16 },
	{ sectionName: "INFORMATION_STORAGE", sectionId: 17 },
	{ sectionName: "LABOR_MANAGEMENT", sectionId: 18 },
	{ sectionName: "PROTECTING_WORKERS", sectionId: 19 },
	{ sectionName: "USE_OF_LABOR", sectionId: 20 },
	{ sectionName: "BUSINESS_AND_CUSTOMERS", sectionId: 21 },
	{ sectionName: "TRAINING", sectionId: 22 },
	{ sectionName: "BOARD_STRUCTURE", sectionId: 23 },
	{ sectionName: "CODE_OF_CONDUCT", sectionId: 24 },
	{ sectionName: "TRANSPARENCY_MANAGEMENT", sectionId: 25 },
	{ sectionName: "AUDIT_STRUCTURE", sectionId: 26 },
	{ sectionName: "RISK_STRUCTURE", sectionId: 27 },
	{ sectionName: "DOCUMENT_DISCLOSURE", sectionId: 28 },
	{ sectionName: "DIVIDEND_PAYMENT", sectionId: 29 },
	{ sectionName: "SUPPLY_CHAIN", sectionId: 30 },
	{ sectionName: "VIOLATION_OF_REGULATIONS", sectionId: 31 },
	{ sectionName: "VIOLATION_IN_ENTERPRISE", sectionId: 32 },
	{ sectionName: "BOARD_OF_DIRECTORS_RATIO", sectionId: 33 },
	{ sectionName: "SOURCES_AND_EMISSION", sectionId: 34 },
];
