module.exports = [
	{
		questionCode: "AS001",
		companyCode: "MWG",
		year: "2022",
		value: "9605",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS002",
		companyCode: "MWG",
		year: "2022",
		value: "2836",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS003",
		companyCode: "MWG",
		year: "2022",
		value: "7078",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS004",
		companyCode: "MWG",
		year: "2022",
		value: "7988",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS005",
		companyCode: "MWG",
		year: "2022",
		value: "1939",
		weight: "0.1",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS006",
		companyCode: "MWG",
		year: "2022",
		value: "865",
		weight: "0.1",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS008",
		companyCode: "MWG",
		year: "2022",
		value: "10225",
		weight: "0.4",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS009",
		companyCode: "MWG",
		year: "2022",
		value: "3183",
		weight: "0.4",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS010",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS011",
		companyCode: "MWG",
		year: "2022",
		value: "2826",
		weight: "0.2",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS012",
		companyCode: "MWG",
		year: "2022",
		value: "352",
		weight: "0.25",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS013",
		companyCode: "MWG",
		year: "2022",
		value: "4046",
		weight: "0.3",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS014",
		companyCode: "MWG",
		year: "2022",
		value: "5726",
		weight: "0.1",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS015",
		companyCode: "MWG",
		year: "2022",
		value: "5302",
		weight: "0.25",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS017",
		companyCode: "MWG",
		year: "2022",
		value: "1504",
		weight: "0.1",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS018",
		companyCode: "MWG",
		year: "2022",
		value: "2637",
		weight: "0.1",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS019",
		companyCode: "MWG",
		year: "2022",
		value: "9749",
		weight: "0.1",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS021",
		companyCode: "MWG",
		year: "2022",
		value: "4163",
		weight: "0.2",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS022",
		companyCode: "MWG",
		year: "2022",
		value: "11042",
		weight: "0.4",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS023",
		companyCode: "MWG",
		year: "2022",
		value: "5876",
		weight: "0.2",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS024",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS025",
		companyCode: "MWG",
		year: "2022",
		value: "461",
		weight: "0.25",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS026",
		companyCode: "MWG",
		year: "2022",
		value: "5492",
		weight: "0.5",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS027",
		companyCode: "MWG",
		year: "2022",
		value: "9066",
		weight: "0.2",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS028",
		companyCode: "MWG",
		year: "2022",
		value: "7801",
		weight: "0.25",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS055",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS056",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS057",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS058",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS059",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS061",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS062",
		companyCode: "MWG",
		year: "2022",
		value: "2",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS063",
		companyCode: "MWG",
		year: "2022",
		value: "2",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS065",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS066",
		companyCode: "MWG",
		year: "2022",
		value: "2",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS068",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS069",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS070",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS071",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS072",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.1",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS073",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.1",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS075",
		companyCode: "MWG",
		year: "2022",
		value: "34",
		weight: "0.3",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS076",
		companyCode: "MWG",
		year: "2022",
		value: "7420",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS080",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.1",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS081",
		companyCode: "MWG",
		year: "2022",
		value: "1382",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS082",
		companyCode: "MWG",
		year: "2022",
		value: "10556",
		weight: "0",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS083",
		companyCode: "MWG",
		year: "2022",
		value: "5659",
		weight: "0.25",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS084",
		companyCode: "MWG",
		year: "2022",
		value: "2449",
		weight: "0.5",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS085",
		companyCode: "MWG",
		year: "2022",
		value: "4687",
		weight: "0.1",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS086",
		companyCode: "MWG",
		year: "2022",
		value: "7124",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS087",
		companyCode: "MWG",
		year: "2022",
		value: "6758",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS088",
		companyCode: "MWG",
		year: "2022",
		value: "3405",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS089",
		companyCode: "MWG",
		year: "2022",
		value: "1213",
		weight: "0.1",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS090",
		companyCode: "MWG",
		year: "2022",
		value: "3747",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS091",
		companyCode: "MWG",
		year: "2022",
		value: "7780",
		weight: "0.25",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS092",
		companyCode: "MWG",
		year: "2022",
		value: "1013",
		weight: "0.25",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS093",
		companyCode: "MWG",
		year: "2022",
		value: "7136",
		weight: "0.1",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS094",
		companyCode: "MWG",
		year: "2022",
		value: "8648",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS095",
		companyCode: "MWG",
		year: "2022",
		value: "1069",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS096",
		companyCode: "MWG",
		year: "2022",
		value: "10206",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS097",
		companyCode: "MWG",
		year: "2022",
		value: "9367",
		weight: "0.1",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS098",
		companyCode: "MWG",
		year: "2022",
		value: "5975",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS099",
		companyCode: "MWG",
		year: "2022",
		value: "9571",
		weight: "0.25",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS100",
		companyCode: "MWG",
		year: "2022",
		value: "7411",
		weight: "0.25",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS101",
		companyCode: "MWG",
		year: "2022",
		value: "2483",
		weight: "0.25",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS102",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS103",
		companyCode: "MWG",
		year: "2022",
		value: "4",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS104",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS105",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS106",
		companyCode: "MWG",
		year: "2022",
		value: "3474",
		weight: "0.25",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS107",
		companyCode: "MWG",
		year: "2022",
		value: "1853",
		weight: "0.25",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS109",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS110",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS111",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS112",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS113",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS114",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS115",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS116",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS117",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS118",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS119",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS120",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.25",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS121",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.25",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS122",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.25",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS123",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.25",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS124",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS125",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS126",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS127",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS128",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS129",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.1",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS130",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.1",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS131",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.1",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS132",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.1",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS133",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.1",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS134",
		companyCode: "MWG",
		year: "2022",
		value: "2126",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS135",
		companyCode: "MWG",
		year: "2022",
		value: "7648",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS136",
		companyCode: "MWG",
		year: "2022",
		value: "7557",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS137",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.1",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS138",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.1",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS139",
		companyCode: "MWG",
		year: "2022",
		value: "3376",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS140",
		companyCode: "MWG",
		year: "2022",
		value: "473",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS141",
		companyCode: "MWG",
		year: "2022",
		value: "4803",
		weight: "0.25",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS142",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS143",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS144",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS145",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS146",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS147",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS148",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS149",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS150",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS151",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS152",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS153",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS154",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS155",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS156",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS157",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.1",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS158",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS159",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS160",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS161",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.1",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS162",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS163",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.4",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS164",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.3",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS165",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.3",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS166",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS167",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS168",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS169",
		companyCode: "MWG",
		year: "2022",
		value: "2",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS173",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS174",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.4",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS175",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.3",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS176",
		companyCode: "MWG",
		year: "2022",
		value: "1",
		weight: "0.3",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS177",
		companyCode: "MWG",
		year: "2022",
		value: "5799",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS178",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS179",
		companyCode: "MWG",
		year: "2022",
		value: "857",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS180",
		companyCode: "MWG",
		year: "2022",
		value: "2087",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS181",
		companyCode: "MWG",
		year: "2022",
		value: "26",
		weight: "0.4",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS182",
		companyCode: "MWG",
		year: "2022",
		value: "21",
		weight: "0.3",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS183",
		companyCode: "MWG",
		year: "2022",
		value: "58",
		weight: "0.3",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS184",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.25",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS185",
		companyCode: "MWG",
		year: "2022",
		value: "184",
		weight: "0.25",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS186",
		companyCode: "MWG",
		year: "2022",
		value: "10",
		weight: "0.25",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS187",
		companyCode: "MWG",
		year: "2022",
		value: "22",
		weight: "0.25",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS189",
		companyCode: "MWG",
		year: "2022",
		value: "788",
		weight: "0.15",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS190",
		companyCode: "MWG",
		year: "2022",
		value: "1940",
		weight: "0.4",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS191",
		companyCode: "MWG",
		year: "2022",
		value: "5833",
		weight: "0.45",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS192",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS193",
		companyCode: "MWG",
		year: "2022",
		value: "52",
		weight: "0.25",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS194",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS195",
		companyCode: "MWG",
		year: "2022",
		value: "2",
		weight: "0.25",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS196",
		companyCode: "MWG",
		year: "2022",
		value: "2",
		weight: "0.25",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS197",
		companyCode: "MWG",
		year: "2022",
		value: "2",
		weight: "0.25",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS198",
		companyCode: "MWG",
		year: "2022",
		value: "857",
		weight: "0.125",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS199",
		companyCode: "MWG",
		year: "2022",
		value: "2087",
		weight: "0.125",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS200",
		companyCode: "MWG",
		year: "2022",
		value: "26",
		weight: "0.125",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS201",
		companyCode: "MWG",
		year: "2022",
		value: "21",
		weight: "0.125",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS202",
		companyCode: "MWG",
		year: "2022",
		value: "58",
		weight: "0.125",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS203",
		companyCode: "MWG",
		year: "2022",
		value: "0",
		weight: "0.125",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS205",
		companyCode: "MWG",
		year: "2022",
		value: "184",
		weight: "0.125",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS207",
		companyCode: "MWG",
		year: "2022",
		value: "10",
		weight: "0.125",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS208",
		companyCode: "MWG",
		year: "2022",
		value: "22",
		weight: "0.25",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS209",
		companyCode: "MWG",
		year: "2022",
		value: "1524",
		weight: "0.1",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS210",
		companyCode: "MWG",
		year: "2022",
		value: "788",
		weight: "0.2",
		polarityIndicating: "positive",
		percentileCompleted: "",
	},
	{
		questionCode: "AS211",
		companyCode: "MWG",
		year: "2022",
		value: "1940",
		weight: "0.2",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS212",
		companyCode: "MWG",
		year: "2022",
		value: "5833",
		weight: "0.1",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS213",
		companyCode: "MWG",
		year: "2022",
		value: "1940",
		weight: "0.1",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS214",
		companyCode: "MWG",
		year: "2022",
		value: "5833",
		weight: "0.1",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
	{
		questionCode: "AS215",
		companyCode: "MWG",
		year: "2022",
		value: "1940",
		weight: "0.1",
		polarityIndicating: "negative",
		percentileCompleted: "",
	},
];
